NEOBAE_TUI := 1

# TUI builds default to SDL3 backend to avoid SDL2-compat linker mismatches.
# Override with USE_SDL2=1 if you explicitly want SDL2.
ifeq ($(USE_SDL2),1)
USE_SDL3 := 0
else
USE_SDL3 := 1
USE_SDL2 := 0
endif

ifeq ($(USE_RAYLIB),1)
	BAE_API := Raylib
else ifeq ($(USE_SDL3),1)
	BAE_API := SDL3
else
	BAE_API := SDL2
endif

include inc/Makefile.common

TARGET_BIN := neobae-tui

CC              := gcc
CXX             := g++
LD              := $(CC)
AR              := ar
STRIP           := strip

OPTI := -O2 -fPIC
ifeq ($(DEBUG),1)
    OPTI := -g -O0 -ggdb3 -fPIC
endif

CFLAGS := $(ARCH) $(OPTI) $(INC_PATH) -D_THREAD_SAFE -Wno-unused-value
ifneq ($(BAE_FLAGS),)
	CFLAGS += $(BAE_FLAGS)
endif

include inc/Makefile.versioning
CFLAGS += -D_VERSION=\"$(VERSION)\"

LDFLAGS := $(OPTI)
ifneq ($(BAE_LD_FLAGS),)
	LDFLAGS += $(BAE_LD_FLAGS)
endif

ifneq ($(DEBUG),1)
	LDFLAGS += -s
endif

LIBS := -lpthread -lm -ldl
ifneq ($(BAE_LIBS),)
	LIBS += $(BAE_LIBS)
endif

NCURSES_CFLAGS := $(shell pkg-config --cflags ncursesw 2>/dev/null)
NCURSES_LIBS := $(shell pkg-config --libs ncursesw 2>/dev/null)
ifeq ($(NCURSES_LIBS),)
	NCURSES_CFLAGS := $(shell pkg-config --cflags ncurses 2>/dev/null)
	NCURSES_LIBS := $(shell pkg-config --libs ncurses 2>/dev/null)
endif
ifeq ($(NCURSES_LIBS),)
	NCURSES_LIBS := -lncursesw
endif

CFLAGS += $(NCURSES_CFLAGS)
LIBS += $(NCURSES_LIBS)

CXXFLAGS := $(CFLAGS)
ifneq ($(filter %.cpp,$(SRC) $(SRC_BIN)),)
    LD := $(CXX)
    LIBS += -lstdc++
endif

all: $(TARGET_BIN)

$(TARGET_BIN): ${OBJ_BIN}
	@mkdir -p $(TARGET_OUT)
	${LD} -o $(TARGET_OUT)${TARGET_BIN} ${LDFLAGS} ${OBJ_BIN} ${LIBS}

ALL_SOURCES := $(sort $(SRC) $(SRC_BIN))
$(foreach src,$(ALL_SOURCES),$(eval $(call make_obj_rule,$(src))))

clean:
	@rm -rf $(TARGET_OUT)
	@rm -rf $(OBJ_DIR)
	@rm -rf $(BUILD_DIR)
	@rm -rf $(TEST_OUT_DIR)
	@echo Cleaned!

include inc/Makefile.tests
