TEST_BIN_PREFIX 	:= "wine "
BAE_BUILT_IN_PATCHES	:= 1
WINDOWS		:= 1
BAE_API := WinOS

ifeq ($(USE_SDL3),1)
    BAE_API		:= SDL3
endif

include inc/Makefile.common
TARGET_BIN		:= $(TARGET_NAME).exe

ifeq ($(BITS),32)
    ARCH		:= -m32 -static
    CC		:= i686-w64-mingw32-gcc-win32
    CXX		:= i686-w64-mingw32-g++-win32
    LD		:= $(CC)
    AR      	:= i686-w64-mingw32-gcc-ar-win32
    STRIP      	:= i686-w64-mingw32-strip
    DLLTOOL		:= i686-w64-mingw32-dlltool
    OPTI            := -O2 
    ifeq ($(LDEBUG),1)
        OPTI := -g -O0 -ggdb3 -fPIC
    endif 
    CFLAGS  	:= $(ARCH) $(OPTI) $(INC_PATH) -D_THREAD_SAFE -Wno-unused-value 
    TARGET_NAME := playbae_dsound_x32
else
    ARCH		:= -m64 -static
    CC		:= x86_64-w64-mingw32-gcc-win32
    CXX		:= x86_64-w64-mingw32-g++-win32
    LD		:= $(CC)
    AR      	:= x86_64-w64-mingw32-gcc-ar-win32
    STRIP      	:= x86_64-w64-mingw32-strip
    DLLTOOL		:= x86_64-w64-mingw32-dlltool
    OPTI            := -O2
    ifeq ($(LDEBUG),1)
        OPTI := -g -O0 -ggdb3 -fPIC
    endif 
    CFLAGS  	:= $(ARCH) $(OPTI) $(INC_PATH) -D_THREAD_SAFE -Wno-unused-value 
    TARGET_NAME := playbae_dsound_x64
endif


ifneq ($(BAE_FLAGS),)
	CFLAGS	+= $(BAE_FLAGS)
endif

include inc/Makefile.versioning
CFLAGS		+= -D_VERSION=\""$(VERSION)"\"
LDFLAGS		:= $(ARCH) $(OPTI) -mconsole 

ifneq ($(LDEBUG),1)
	LDFLAGS += -s
endif

LIBS   = \
    -ldxguid \
    -ldsound \
    -lwinmm \
    -lole32

ifeq ($(USE_SDL3),1)
    ifeq ($(BITS),32)
        CFLAGS   += -I../deps/win/SDL3/i686-w64-mingw32/include
        LDFLAGS  += -L../deps/win/SDL3/i686-w64-mingw32/lib
        TARGET_NAME := playbae_sdl3_x32
    else
        CFLAGS    += -I../deps/win/SDL3/x86_64-w64-mingw32/include
        LDFLAGS   += -L../deps/win/SDL3/x86_64-w64-mingw32/lib
        TARGET_NAME := playbae_sdl3_x64
    endif
    # Override LIBS completely for SDL build to enforce correct ordering
    LIBS = \
        -lSDL3.dll 
endif

ifneq ($(BAE_LD_FLAGS),)
    LD_FLAGS += $(BAE_LD_FLAGS)
endif

ifneq ($(BAE_LIBS),)
    LIBS += $(BAE_LIBS)
endif

# Use C++ linker if we have any C++ sources
ifneq ($(filter %.cpp,$(SRC) $(SRC_BIN)),)
    LD := $(CXX)
    LIBS += -lstdc++ -lsupc++
endif

CXXFLAGS 	:= $(CFLAGS)

all: $(TARGET_LIB).a ${TARGET_LIB}.dll $(TARGET_BIN)

$(TARGET_LIB).a: $(OBJ)
	@mkdir -p $(TARGET_OUT)
	$(AR) rcs $(TARGET_OUT)$(TARGET_LIB).a $(OBJ)

$(TARGET_LIB).dll: ${OBJ}
	@mkdir -p $(TARGET_OUT)
	@$(DLLTOOL) --export-all --export-all-symbols -e $(OBJ_DIR)exports.o -z $(OBJ_DIR)$(TARGET_LIB).def2 $(OBJ)
	@echo "EXPORTS" > $(OBJ_DIR)$(TARGET_LIB).def
	@cat $(OBJ_DIR)$(TARGET_LIB).def2 | grep "BAE" >> $(OBJ_DIR)$(TARGET_LIB).def
	@rm -f $(OBJ_DIR)$(TARGET_LIB).def2 $(OBJ_DIR)exports.o
	@$(DLLTOOL) -e $(OBJ_DIR)exports.o -d $(OBJ_DIR)$(TARGET_LIB).def -l $(TARGET_OUT)$(TARGET_LIB).lib $(OBJ)
	${CC} -shared $(LDFLAGS) ${OBJ} $(OBJ_DIR)exports.o -o $(TARGET_OUT)${TARGET_LIB}.dll ${LIBS}

	@if [ "$(USE_FLUIDSYNTH)" = "1" ]; then \
		if [ "$(BITS)" = "32" ]; then \
			cp ../deps/win/FluidSynth/i686-w64-mingw32/bin/libfluidsynth-3.dll $(TARGET_OUT) 2>/dev/null || true; \
			cp ../deps/win/FluidSynth/i686-w64-mingw32/bin/sndfile.dll $(TARGET_OUT) 2>/dev/null || true; \
		else \
			cp ../deps/win/FluidSynth/x86_64-w64-mingw32/bin/libfluidsynth-3.dll $(TARGET_OUT) 2>/dev/null || true; \
			cp ../deps/win/FluidSynth/x86_64-w64-mingw32/bin/sndfile.dll $(TARGET_OUT) 2>/dev/null || true; \
		fi; \
	fi

	@if [ "$(USE_SDL3)" = "1" ]; then \
		if [ "$(BITS)" = "32" ]; then \
    		cp ../deps/win/SDL3/i686-w64-mingw32/bin/SDL3.dll $(TARGET_OUT) 2>/dev/null || true; \
		    cp ../deps/win/SDL3_ttf/i686-w64-mingw32/bin/SDL3_ttf.dll $(TARGET_OUT) 2>/dev/null || true; \
	    else \
    		cp ../deps/win/SDL3/x86_64-w64-mingw32/bin/SDL3.dll $(TARGET_OUT) 2>/dev/null || true; \
		    cp ../deps/win/SDL3_ttf/x86_64-w64-mingw32/bin/SDL3_ttf.dll $(TARGET_OUT) 2>/dev/null || true; \
	    fi; \
    fi

	@if [ "$(BITS)" = "32" ]; then \
		cp ../deps/win/LZMA-$(LZMA_VERS)/i686-w64-mingw32/bin/liblzma-5.dll $(TARGET_OUT) 2>/dev/null || true; \
	else \
		cp ../deps/win/LZMA-$(LZMA_VERS)/x86_64-w64-mingw32/bin/liblzma-5.dll $(TARGET_OUT) 2>/dev/null || true; \
	fi

	@if [ "$(BITS)" = "32" ]; then \
		cp ../deps/win/lame/i686-w64-mingw32/bin/libmp3lame-0.dll $(TARGET_OUT) 2>/dev/null || true; \
	else \
		cp ../deps/win/lame/x86_64-w64-mingw32/bin/libmp3lame-0.dll $(TARGET_OUT) 2>/dev/null || true; \
	fi	

$(TARGET_BIN): ${OBJ_BIN}
	@mkdir -p $(TARGET_OUT)Banks
	$(SHELL) src/banks/copy.sh $(TARGET_OUT)Banks
	${LD} -o $(TARGET_OUT)${TARGET_BIN} ${LDFLAGS} ${OBJ_BIN} ${LIBS}

# Rules for compiling source files to object files
$(OBJ_DIR)%.o : %.cpp
	@echo @compile $<
	@mkdir -p $(OBJ_DIR)
	$(SILENT)${CXX} -c ${CXXFLAGS} $< -o $@

$(OBJ_DIR)%.o : %.c
	@echo @compile $<
	@mkdir -p $(OBJ_DIR)
	$(SILENT)${CC} -c ${CFLAGS} $< -o $@

clean:
	@rm -rf $(TARGET_OUT)
	@rm -rf $(OBJ_DIR)
	@rm -rf $(BUILD_DIR)
	@rm -rf $(TEST_OUT_DIR)
	@echo Cleaned!

# Generate rules for all unique source files (same approach as top-level Makefile)
ALL_SOURCES := $(sort $(SRC) $(SRC_BIN))
$(foreach src,$(ALL_SOURCES),$(eval $(call make_obj_rule,$(src))))

include inc/Makefile.tests
