BAE_API := SDL2
USE_SDL3 := 1
NOAUTO := 1
SF2_SUPPORT := 0
EMBED_PATCHES := 1
MOD2RMF := 1
MTHC_SUPPORT := 1
RETRO_RINGTONE_SUPPORT := 1
CREATION_API := 1
NBSTUDIO := 1
include inc/Makefile.common

TARGET_BIN := nbstudio

CC		?= gcc
CXX		?= g++
LD		:= $(CC)
AR      	:= ar
STRIP		:= strip

OPTI            := -O2 -fPIC

ifeq ($(DEBUG),1)
    OPTI := -g -O0 -ggdb3 -fPIC
endif

WX_CONFIG ?= wx-config

WX_CXXFLAGS := $(shell $(WX_CONFIG) --cxxflags)
WX_LIBS := $(shell $(WX_CONFIG) --libs core,base)

CFLAGS  	:= $(ARCH) $(OPTI) $(INC_PATH) -D_THREAD_SAFE -Wno-unused-value $(EXTRA_CFLAGS)

ifneq ($(BAE_FLAGS),)
	CFLAGS	+= $(BAE_FLAGS)
endif

include inc/Makefile.versioning
CFLAGS		+= -D_VERSION=\""$(VERSION)"\"


LDFLAGS		:= $(OPTI)
ifneq ($(BAE_LD_FLAGS),)
	LDFLAGS += $(BAE_LD_FLAGS)
endif

ifneq ($(DEBUG),1)
	LDFLAGS += -s
endif

LIBS	= 	-lpthread -lm -lSDL3

ifneq ($(BAE_LIBS),)
	LIBS += $(BAE_LIBS)
endif

CXXFLAGS 	:= $(CFLAGS) $(WX_CXXFLAGS)
# Use C++ linker if we have any C++ sources
ifneq ($(filter %.cpp,$(SRC) $(SRC_BIN)),)
    LD := $(CXX)
    LIBS += -lstdc++
endif

LIBS += $(WX_LIBS)

all: $(TARGET_BIN)

$(TARGET_BIN): ${OBJ_BIN}
	@mkdir -p $(TARGET_OUT)
	${LD} -o $(TARGET_OUT)${TARGET_BIN} ${LDFLAGS} ${OBJ_BIN} ${LIBS}

# Generate rules for all unique source files
ALL_SOURCES := $(sort $(SRC) $(SRC_BIN))
$(foreach src,$(ALL_SOURCES),$(eval $(call make_obj_rule,$(src))))

clean:
	@rm -rf $(TARGET_OUT)
	@rm -rf $(OBJ_DIR)
	@rm -rf $(BUILD_DIR)
	@rm -rf $(TEST_OUT_DIR)
	@echo Cleaned!

include inc/Makefile.tests
