org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true

# Mod metadata
mod_id=neobaemc
mod_name=NeoBAE for Minecraft
mod_license=GPL-3.0-only
mod_version=0.1.0
mod_group_id=com.zefie.neobaemc
mod_authors=zefie
mod_description=Replaces Etched's audio decoder with NeoBAE, adding FLAC, MIDI, RMF, XMF and more to Etched's URL-etched music discs.

# Versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21.1.0,22)
loader_version_range=[4,)
java_version=21
