# Built-in Patches (affects entire NeoBAE library)
# Must be an HSB bank, leave empty to disable built-in patches completely
EMBED_PATCH_FILE ?= src/banks/patches111/patches111.hsb

# TTF Font (for zefidi GUI)
# Not required but severely recommended
EMBED_TTF_FONT ?= src/thirdparty/fonts/HelveticaNeue.ttf

### It is probably best not to change anything below this line, unless absolutely necessary for your environment

BUILD_DIR	  := build/
TEST_OUT_DIR  := tests/
TARGET_OUT	  := bin/
BAE_FLAGS	  :=
BAE_LD_FLAGS  := -Wl,-rpath,'$$ORIGIN'
BAE_LIBS      :=
.DEFAULT_GOAL := all
LZMA_VERS := 5.8.3

# Default build options (override with NOAUTO=1)
ifneq ($(WASM),1)
	ifneq ($(NOAUTO),1)
		ZMF_SUPPORT := 1
		KARAOKE := 1
		BAESCRIPT := 1
		PLAYLIST := 1
		SF2_SUPPORT := 1
		USE_FLUIDSYNTH := 1
		EMBED_PATCHES := 1
		EMBED_FONT := 1
		XMF_SUPPORT := 1
		RMI_SUPPORT := 1
		RETRO_RINGTONE_SUPPORT := 1
		DISABLE_NOKIA := 0			    
		DISABLE_BEATNIK_SF2_NRPN := 0
		USE_BUILTIN_PATCHES_WITH_SF2 := 1
		USE_BUILTIN_PATCHES_WITH_DLS := 1
		FIX_SPAN_DC := 1
		CLASSIC_CHORUS := 1
		LZMA_SUPPORT := 1
		MTHC_SUPPORT := 1
		ADP_SUPPORT := 1
		QOA_SUPPORT := 1
		MP3_DEC := 1
		MP3_ENC := 1
		FLAC_DEC := 1
		FLAC_ENC := 1
		VORBIS_DEC := 1
		VORBIS_ENC := 1
		OPUS_DEC := 1
		OPUS_ENC := 1
		J2ME_PATCH := 1
		CREATION_NO_CODECS := 0
		CREATION_API := 0
		UNROLL_MIDI :=1
		ADX_SUPPORT := 1
		NATIVE_DLS := 1
	endif
endif

ifeq ($(NBSTUDIO),1)
	# NBStudio requires ZMF support
	# and the creation API
	ZMF_SUPPORT := 1
	CREATION_API := 1
	FIX_SPAN_DC := 1
	CLASSIC_CHORUS := 1
endif

ifeq ($(NBEDITOR),1)
	# NBEditor requires ZMF support
	# and the creation API
	ZMF_SUPPORT := 1
	CREATION_API := 1
	FIX_SPAN_DC := 1
	CLASSIC_CHORUS := 1
	BAE_FLAGS += -DNBEDITOR=1 -DNBEDITOR_MVP=1 -DNBEDITOR_PLAYER_WINDOW=1 -DNBEDITOR_SAMPLE_LIST_WINDOW=1 -DNBEDITOR_INSTRUMENT_LIST_WINDOW=1
	INC_PATH += -Isrc/thirdparty/imgui -Isrc/thirdparty/imgui/backends
endif

ifeq ($(CREATION_API),1) 
	# All of these are required for ZMF support
	ifneq ($(CREATION_NO_CODECS),1)
		OGG_SUPPORT := 1
		MP3_DEC := 1
		MP3_ENC := 1
		FLAC_DEC := 1
		FLAC_ENC := 1
		VORBIS_DEC := 1
		VORBIS_ENC := 1
		OPUS_DEC := 1
		OPUS_ENC := 1
		QOA_SUPPORT := 1
	endif
	ZMF_SUPPORT := 1
endif

ifeq ($(ZMF_SUPPORT),1)
	LZMA_SUPPORT := 1
	FIX_SPAN_DC := 1
	CLASSIC_CHORUS := 1
endif	

# Disable SDL2 if using SDL3
ifeq ($(USE_SDL3),1)
	USE_SDL2 := 0
endif

# Disable SDL backends if using raylib
ifeq ($(USE_RAYLIB),1)
	USE_SDL2 := 0
	USE_SDL3 := 0
endif

# Likewise, Disable SDL3 if using SDL2
ifeq ($(USE_SDL2),1)
	USE_SDL3 := 0
endif

# Enable SoundFont (SF2) support via FluidSynth overlay. Set this to TRUE to enable.
ifeq ($(SF2_SUPPORT),1)
	USE_FLUIDSYNTH := 1
endif

# Native DLS is required for XMF
ifneq ($(NATIVE_DLS),1)
   XMF_SUPPORT := 0
endif


# Force OGG support if VORBIS is chosen
ifneq ($(OGG_SUPPORT),1)
	ifneq ($(filter 1,$(VORBIS_ENC) $(VORBIS_DEC) $(FLAC_DEC) $(FLAC_ENC) $(OPUS_DEC) $(OPUS_ENC)),) 
		OGG_SUPPORT := 1
	endif
endif

ifneq ($(filter 1,$(VERBOSE) $(V)),)
	SILENT :=
else
	SILENT := @
endif

# Begin Allow Overrides
ifeq ($(TARGET_LIB),)
	TARGET_LIB	:= libNeoBAE
endif

ifeq ($(TARGET_BIN),)
	ifneq ($(BUILD_GUI),) 
		TARGET_BIN	:= zefidi
		TARGET_NAME := $(TARGET_BIN)
	else
		TARGET_BIN	:= playbae
		TARGET_NAME := $(TARGET_BIN)
	endif
else
	TARGET_NAME := $(TARGET_BIN)	
endif

ifeq ($(TEST_BIN_PREFIX),)
	TEST_BIN	:= $(TARGET_OUT)$(TARGET_BIN)
else
	TEST_BIN	:= $(TEST_BIN_PREFIX)$(TARGET_OUT)$(TARGET_BIN)
endif
# End Allow Overrides

INC_PATH	:= -Isrc/BAE_Source/Common
INC_PATH	+= -Isrc/BAE_Source/Platform
INC_PATH	+= -Isrc/thirdparty/config

ifneq ($(filter 1,$(MP3_ENC) $(MP3_DEC)),) 
	INC_PATH  += -Isrc/BAE_MPEG_Source_II
endif

ifeq ($(MP3_DEC),1)
	INC_PATH	+= -Isrc/thirdparty/minimp3
endif

ifeq ($(ENABLE_MIDI_HW),1)
	INC_PATH	+= -Isrc/thirdparty/rtmidi
endif

ifeq ($(DISABLE_NOKIA),1)
	BAE_FLAGS += -DDISABLE_NOKIA_PATCH=1
endif

ifeq ($(DISABLE_BEATNIK_SF2_NRPN),1)
	BAE_FLAGS += -DISABLE_BEATNIK_SF2_NRPN=1
endif

ifeq ($(FIX_SPAN_DC),1)
	BAE_FLAGS += -DBAE_FIX_SPAN_DC=1
endif

ifeq ($(CLASSIC_CHORUS),1)
	BAE_FLAGS += -DBAE_CLASSIC_CHORUS=1
endif

ifeq ($(ZMF_SUPPORT),1)
	BAE_FLAGS += -DUSE_ZMF_SUPPORT=1
endif

ifeq ($(RMI_SUPPORT),1)
	BAE_FLAGS += -DUSE_RMI_SUPPORT=1
endif

ifeq ($(J2ME_PATCH),1)
	BAE_FLAGS += -DUSE_J2ME_PATCH=1
endif

ifeq ($(RETRO_RINGTONE_SUPPORT),1)
	BAE_FLAGS += -DUSE_RETRO_RINGTONE_SUPPORT=1
endif

ifeq ($(UNROLL_MIDI),1)
	BAE_FLAGS += -DBAE_ENABLE_ROLLED_MIDI_UNROLL=1
endif

ifneq ($(filter 1,$(FLAC_ENC) $(FLAC_DEC)),) 
	INC_PATH	+= -Isrc/thirdparty/flac/include -Isrc/thirdparty/flac/src/libFLAC/include -Isrc/thirdparty/flac/src
	BAE_FLAGS += -DHAVE_CONFIG_H=1 -DHAVE_STDINT_H=1 -DHAVE_INTTYPES_H=1 -DSIZE_T_MAX=SIZE_MAX
	ifeq ($(OGG_SUPPORT),1)
		BAE_FLAGS += -DFLAC__HAS_OGG=1
	else
		BAE_FLAGS += -DFLAC__HAS_OGG=0
	endif
endif

ifeq ($(WINDOWS),1)
	ifeq ($(BITS),32)
		INC_PATH += -I/mingw32/include -I/usr/i686-w64-mingw32/include
		BAE_LIBS += -L/mingw32/lib -L/usr/i686-w64-mingw32/lib
	else
		INC_PATH += -I/mingw64/include -I/usr/x86_64-w64-mingw32/include
		BAE_LIBS += -L/mingw64/lib -L/usr/x86_64-w64-mingw32/lib
	endif
endif

ifneq ($(filter 1,$(OPUS_DEC) $(OPUS_ENC)),)
	INC_PATH	+= -Isrc/thirdparty/opus/include
	INC_PATH	+= -Isrc/thirdparty/opus/celt
	INC_PATH	+= -Isrc/thirdparty/opus/silk
	INC_PATH	+= -Isrc/thirdparty/opus/silk/float
	INC_PATH	+= -Isrc/thirdparty/opus/src
	ifeq ($(OPUS_DEC),1)
		INC_PATH	+= -Isrc/thirdparty/opusfile/include
		INC_PATH	+= -Isrc/thirdparty/opusfile/src
	endif
	BAE_FLAGS += -DVAR_ARRAYS=1 -DOPUS_BUILD=1
	ifeq ($(OPUS_DEC),1)
		BAE_FLAGS += -DUSE_OPUS_DECODER=1
	endif
	ifeq ($(OPUS_ENC),1)
		BAE_FLAGS += -DUSE_OPUS_ENCODER=1
	endif
endif

ifneq ($(filter 1,$(VORBIS_DEC) $(VORBIS_ENC)),) 
	INC_PATH	+= -Isrc/thirdparty/libvorbis/include -Isrc/thirdparty/libvorbis/lib
endif

# default to ANSI
ifeq ($(BAE_API),)
	BAE_API		:= Dummy
endif

## Begin Easy API -> X_PLATFORM
# Supported APIs
ifeq ($(BAE_API),Ansi)
	# No audio output
	BAE_FLAGS += 	-DX_PLATFORM=X_ANSI
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),Dummy)
	# No audio output, no pthreads
	BAE_FLAGS += 	-DX_PLATFORM=X_DUMMY
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),WASM)
	BAE_FLAGS += 	-DX_PLATFORM=X_WASM
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c \
					src/BAE_Source/Platform/BAE_API_WASM_Export.c
endif
ifeq ($(BAE_API),WinOS)
	BAE_FLAGS += 	-DX_PLATFORM=X_WIN95
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c \
			src/BAE_Source/Platform/BAE_API_$(BAE_API)_Capture.c \
			src/BAE_Source/Platform/BAE_API_$(BAE_API)_Thread.c
endif
ifeq ($(BAE_API),SDL2)
	BAE_FLAGS += 	-DX_PLATFORM=X_SDL2 -DUSE_SDL2=1
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),SDL3)
	BAE_FLAGS += 	-DX_PLATFORM=X_SDL3
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),Raylib)
	BAE_FLAGS += 	-DX_PLATFORM=X_RAYLIB -DUSE_RAYLIB=1
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),Android)
	BAE_FLAGS += 	-DX_PLATFORM=X_ANDROID
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
# zefie has not tested these APIs
ifeq ($(BAE_API),foobar2000)
	BAE_FLAGS += 	-DX_PLATFORM=X_FOOBAR2000_PLUGIN
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),MacOSX)
	BAE_FLAGS += 	-DX_PLATFORM=X_MACINTOSH
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),IOS)
	BAE_FLAGS += 	-DX_PLATFORM=X_IOS
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
## End Easy API -> X_PLATFORM
### End configure BAE API

# Debug
ifeq ($(DEBUG),1)
	BAE_FLAGS +=    -D_DEBUG=1 -Wall -Wno-unused-function
endif


ifeq ($(SF2_SUPPORT),1)
	BAE_FLAGS += -DUSE_SF2_SUPPORT=1
endif

ifeq ($(XMF_SUPPORT),1)
	BAE_FLAGS += -DUSE_XMF_SUPPORT=1
	SRC += src/BAE_Source/Common/GenXMF.c
	BAE_LIBS += -lz
endif


# Primary libNeoBAE sources
SRC		+=	src/BAE_Source/Common/DriverTools.c \
			src/BAE_Source/Common/GenAudioStreams.c \
			src/BAE_Source/Common/GenCache.c \
			src/BAE_Source/Common/GenChorus.c \
			src/BAE_Source/Common/GenFiltersReverbU3232.c \
			src/BAE_Source/Common/GenInterp2ReverbU3232.c \
			src/BAE_Source/Common/GenOutput.c \
			src/BAE_Source/Common/GenPatch.c \
			src/BAE_Source/Common/GenReverb.c \
			src/BAE_Source/Common/GenReverbNew.c \
			src/BAE_Source/Common/GenReverbNeo.c \
			src/BAE_Source/Common/GenSample.c \
			src/BAE_Source/Common/GenSeq.c \
			src/BAE_Source/Common/GenSeqTools.c \
			src/BAE_Source/Common/GenSetup.c \
			src/BAE_Source/Common/GenSong.c \
			src/BAE_Source/Common/GenSoundFiles.c \
			src/BAE_Source/Common/GenSynth.c \
			src/BAE_Source/Common/GenSynthFiltersSimple.c \
			src/BAE_Source/Common/GenSynthFiltersU3232.c \
			src/BAE_Source/Common/GenSynthInterp2Simple.c \
			src/BAE_Source/Common/GenSynthInterp2U3232.c \
			src/BAE_Source/Common/NeoBAE.c \
			src/BAE_Source/Common/NewNewLZSS.c \
			src/BAE_Source/Common/SampleTools.c \
			src/BAE_Source/Common/X_API.c \
			src/BAE_Source/Common/X_Decompress.c \
			src/BAE_Source/Common/X_IMA.c \
			src/BAE_Source/Common/g711.c \
			src/BAE_Source/Common/g721.c \
			src/BAE_Source/Common/g723_24.c \
			src/BAE_Source/Common/g723_40.c \
			src/BAE_Source/Common/g72x.c \
			src/BAE_Source/Common/BAE_Override.c \
			src/BAE_Source/Common/sha1mini.c \
			src/BAE_Source/Common/XFileTypes.c \
			src/BAE_Source/Common/X_DebugCallback.c

ifeq ($(RETRO_RINGTONE_SUPPORT),1)
	SRC += src/BAE_Source/Common/GenRingtone.c
endif

ifeq ($(ADX_SUPPORT),1)
	SRC += src/BAE_Source/Common/XADXFiles.c
	BAE_FLAGS += -DUSE_ADX_SUPPORT=1
endif

ifeq ($(NATIVE_DLS),1)
	SRC += src/BAE_Source/Common/GenDLS_MobileBAE.c
	BAE_FLAGS += -DUSE_NATIVE_DLS=1
endif

ifeq ($(RMI_SUPPORT),1)
	SRC += src/BAE_Source/Common/GenRMI.c
endif

ifeq ($(SF2_SUPPORT),1)
	ifeq ($(USE_FLUIDSYNTH),1)
		SRC += src/BAE_Source/Common/GenSF2_FluidSynth.c
		BAE_FLAGS += -D_USING_FLUIDSYNTH=1 
		ifeq ($(WINDOWS),1)					
			ifeq ($(BITS),32)
				INC_PATH += -I../deps/win/FluidSynth/i686-w64-mingw32/include
				BAE_LD_FLAGS += -L../deps/win/FluidSynth/i686-w64-mingw32/lib/
				BAE_LIBS += ../deps/win/FluidSynth/i686-w64-mingw32/lib/libfluidsynth-3.dll.a -Wl,-rpath,'$$ORIGIN'
			else
				INC_PATH += -I../deps/win/FluidSynth/x86_64-w64-mingw32/include
				BAE_LD_FLAGS += -L../deps/win/FluidSynth/x86_64-w64-mingw32/lib/
				BAE_LIBS += ../deps/win/FluidSynth/x86_64-w64-mingw32/lib/libfluidsynth-3.dll.a -Wl,-rpath,'$$ORIGIN'
			endif			
		else
			ifneq ($(XPHACK),1)
				ifneq ($(WASM),1)
					# System FluidSynth for Linux (dynamic) if pkg-config available
					FLUIDSYNTH_CFLAGS := $(shell pkg-config --cflags fluidsynth 2>/dev/null)
					FLUIDSYNTH_LIBS   := $(shell pkg-config --libs fluidsynth 2>/dev/null)
					ifneq ($(FLUIDSYNTH_LIBS),)
						BAE_FLAGS += $(FLUIDSYNTH_CFLAGS)
						# Prepend pkg-config libs; they already have -lfluidsynth and any needed deps
						BAE_LIBS := $(FLUIDSYNTH_LIBS) $(filter-out -lfluidsynth,$(BAE_LIBS))
						ifneq (,$(findstring -static,$(ARCH)))
							ARCH := $(filter-out -static,$(ARCH))
							LDFLAGS := $(filter-out -static,$(LDFLAGS))
						endif
					else
						# Fallback minimal guess
						BAE_FLAGS += -I/usr/include/fluidsynth
						BAE_LIBS += -lfluidsynth $(BAE_LIBS)
					endif
				endif
			endif
		endif
	endif
endif
ifneq ($(WINDOWS),1)
	ifeq ($(USE_SDL2),1)
		SDL_CFLAGS := $(shell pkg-config --cflags SDL2 2>/dev/null)
		SDL_LIBS   := $(shell pkg-config --libs SDL2 2>/dev/null)
		ifneq ($(SDL_LIBS),)
			BAE_FLAGS += $(SDL_CFLAGS)
			# Prepend pkg-config libs; they already have -lfluidsynth and any needed deps
			BAE_LIBS := $(SDL_LIBS) $(filter-out -lSDL2,$(BAE_LIBS))
			ifneq (,$(findstring -static,$(ARCH)))
				ARCH := $(filter-out -static,$(ARCH))
				LDFLAGS := $(filter-out -static,$(LDFLAGS))
			endif
		else
			# Fallback minimal guess
			BAE_FLAGS += -I/usr/include/SDL2
			BAE_LIBS += -lSDL2 $(BAE_LIBS)
		endif
	endif

	ifeq ($(USE_SDL3),1)
		SDL_CFLAGS := $(shell pkg-config --cflags SDL3 2>/dev/null)
		SDL_LIBS   := $(shell pkg-config --libs SDL3 2>/dev/null)
		ifneq ($(SDL_LIBS),)
			BAE_FLAGS += $(SDL_CFLAGS)
			# Prepend pkg-config libs; they already have -lfluidsynth and any needed deps
			BAE_LIBS := $(SDL_LIBS) $(filter-out -lSDL3,$(BAE_LIBS))
			ifneq (,$(findstring -static,$(ARCH)))
				ARCH := $(filter-out -static,$(ARCH))
				LDFLAGS := $(filter-out -static,$(LDFLAGS))
			endif
		else
			# Fallback minimal guess
			BAE_FLAGS += -I/usr/include/SDL2
			BAE_LIBS += -lSDL3 $(BAE_LIBS)
		endif
	endif
endif

ifeq ($(MP3_DEC),1)
	# Enable minimp3 wrapper for MPG_* API (decoder only)
	BAE_FLAGS += -DUSE_MINIMP3_WRAPPER=1 -DUSE_MPEG_DECODER=1
	SRC += src/BAE_MPEG_Source_II/XMPEG_minimp3_wrapper.c
endif

# Include XMPEGFilesSun.c when either encoder or decoder is enabled
ifneq ($(filter 1,$(MP3_ENC) $(MP3_DEC)),) 
	SRC += src/BAE_MPEG_Source_II/XMPEGFilesSun.c
endif

# RMF editing and creation API, used by NeoBAE Studio
# This API enables numerous exports in the DLL and LIB
# for interacting with the BAE system
ifeq ($(CREATION_API),1)
	SRC += src/BAE_Source/Common/BAERmfEditor.c
endif

# Optional MP3 encoder integration
# Enable with make MP3_ENC=1 (or set in environment)
ifeq ($(MP3_ENC),1)
	INC_PATH += -Isrc/thirdparty/lame-3.100-slim/include
	INC_PATH += -Isrc/thirdparty/lame-3.100-slim/libmp3lame
	INC_PATH += -Isrc/thirdparty/lame-3.100-slim/mpglib
	BAE_FLAGS += -DHAVE_CONFIG_H=1 -DHAVE_STDINT_H=1 -DHAVE_INTTYPES_H=1
	BAE_FLAGS += -DUSE_MPEG_ENCODER=1 -DUSE_LAME_ENCODER=1
	SRC += src/BAE_MPEG_Source_II/XMPEG_lame_encoder.cpp
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/VbrTag.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/bitstream.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/encoder.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/fft.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/gain_analysis.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/id3tag.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/lame.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/newmdct.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/presets.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/psymodel.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/quantize.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/quantize_pvt.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/reservoir.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/set_get.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/tables.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/takehiro.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/util.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/vbrquantize.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/version.c
	SRC += src/thirdparty/lame-3.100-slim/libmp3lame/mpglib_interface.c
endif

# Add FLAC decoder source files
ifneq ($(filter 1,$(FLAC_DEC) $(FLAC_ENC)),)
	SRC += src/thirdparty/flac/src/libFLAC/stream_encoder.c
	SRC += src/thirdparty/flac/src/libFLAC/bitmath.c
	SRC += src/thirdparty/flac/src/libFLAC/bitreader.c
	SRC += src/thirdparty/flac/src/libFLAC/bitwriter.c
	SRC += src/thirdparty/flac/src/libFLAC/cpu.c
	SRC += src/thirdparty/flac/src/libFLAC/crc.c
	SRC += src/thirdparty/flac/src/libFLAC/fixed.c
	SRC += src/thirdparty/flac/src/libFLAC/float.c
	SRC += src/thirdparty/flac/src/libFLAC/format.c
	SRC += src/thirdparty/flac/src/libFLAC/lpc.c
	SRC += src/thirdparty/flac/src/libFLAC/md5.c
	SRC += src/thirdparty/flac/src/libFLAC/memory.c
	SRC += src/thirdparty/flac/src/libFLAC/metadata_iterators.c
	SRC += src/thirdparty/flac/src/libFLAC/metadata_object.c
	SRC += src/thirdparty/flac/src/libFLAC/stream_decoder.c
	SRC += src/thirdparty/flac/src/libFLAC/stream_encoder_framing.c
	SRC += src/thirdparty/flac/src/libFLAC/window.c
	ifeq ($(OGG_SUPPORT),1)
		SRC += src/thirdparty/flac/src/libFLAC/ogg_decoder_aspect.c
		SRC += src/thirdparty/flac/src/libFLAC/ogg_encoder_aspect.c
		SRC += src/thirdparty/flac/src/libFLAC/ogg_helper.c
		SRC += src/thirdparty/flac/src/libFLAC/ogg_mapping.c
	endif
endif

# Add FLAC decoder source files
ifeq ($(FLAC_DEC),1)
	BAE_FLAGS += -DUSE_FLAC_DECODER=1
endif

# Add FLAC encoder source files
ifeq ($(FLAC_ENC),1)
	BAE_FLAGS += -DUSE_FLAC_ENCODER=1
endif

# Add libogg source files
ifeq ($(OGG_SUPPORT),1)
	SRC += src/thirdparty/libogg/src/bitwise.c
	SRC += src/thirdparty/libogg/src/framing.c
	BAE_FLAGS += -DUSE_OGG_FORMAT=1
endif

# Add libvorbis decoder source files
ifneq ($(filter 1,$(VORBIS_DEC) $(VORBIS_ENC)),) 
	SRC += src/thirdparty/libvorbis/lib/mdct.c
	SRC += src/thirdparty/libvorbis/lib/smallft.c
	SRC += src/thirdparty/libvorbis/lib/block.c
	SRC += src/thirdparty/libvorbis/lib/envelope.c
	SRC += src/thirdparty/libvorbis/lib/window.c
	SRC += src/thirdparty/libvorbis/lib/lsp.c
	SRC += src/thirdparty/libvorbis/lib/lpc.c
	SRC += src/thirdparty/libvorbis/lib/analysis.c
	SRC += src/thirdparty/libvorbis/lib/synthesis.c
	SRC += src/thirdparty/libvorbis/lib/psy.c
	SRC += src/thirdparty/libvorbis/lib/info.c
	SRC += src/thirdparty/libvorbis/lib/floor1.c
	SRC += src/thirdparty/libvorbis/lib/floor0.c
	SRC += src/thirdparty/libvorbis/lib/res0.c
	SRC += src/thirdparty/libvorbis/lib/mapping0.c
	SRC += src/thirdparty/libvorbis/lib/registry.c
	SRC += src/thirdparty/libvorbis/lib/codebook.c
	SRC += src/thirdparty/libvorbis/lib/sharedbook.c
	SRC += src/thirdparty/libvorbis/lib/lookup.c
	SRC += src/thirdparty/libvorbis/lib/bitrate.c
	SRC += src/thirdparty/libvorbis/lib/vorbisfile.c
	ifneq ($(filter 1,$(VORBIS_ENC)),)
		SRC += src/thirdparty/libvorbis/lib/vorbisenc.c
	endif
	SRC += src/BAE_Source/Common/XVorbisFiles.c
	ifeq ($(VORBIS_DEC),1)
		BAE_FLAGS += -DUSE_VORBIS_DECODER=1
	endif
	ifeq ($(VORBIS_ENC),1)
		BAE_FLAGS += -DUSE_VORBIS_ENCODER=1
	endif
endif

ifneq ($(filter 1,$(OPUS_DEC) $(OPUS_ENC)),)
	SRC += src/BAE_Source/Common/XOpusFiles.c
	SRC += src/thirdparty/opus/src/opus.c
	SRC += src/thirdparty/opus/src/opus_decoder.c
	SRC += src/thirdparty/opus/src/opus_encoder.c
	SRC += src/thirdparty/opus/src/extensions.c
	SRC += src/thirdparty/opus/src/opus_multistream.c
	SRC += src/thirdparty/opus/src/opus_multistream_encoder.c
	SRC += src/thirdparty/opus/src/opus_multistream_decoder.c
	SRC += src/thirdparty/opus/src/repacketizer.c
	SRC += src/thirdparty/opus/src/opus_projection_encoder.c
	SRC += src/thirdparty/opus/src/opus_projection_decoder.c
	SRC += src/thirdparty/opus/src/mapping_matrix.c
	SRC += src/thirdparty/opus/src/analysis.c
	SRC += src/thirdparty/opus/src/mlp.c
	SRC += src/thirdparty/opus/src/mlp_data.c
	SRC += src/thirdparty/opus/celt/bands.c
	SRC += src/thirdparty/opus/celt/celt.c
	SRC += src/thirdparty/opus/celt/celt_encoder.c
	SRC += src/thirdparty/opus/celt/celt_decoder.c
	SRC += src/thirdparty/opus/celt/cwrs.c
	SRC += src/thirdparty/opus/celt/entcode.c
	SRC += src/thirdparty/opus/celt/entdec.c
	SRC += src/thirdparty/opus/celt/entenc.c
	SRC += src/thirdparty/opus/celt/kiss_fft.c
	SRC += src/thirdparty/opus/celt/laplace.c
	SRC += src/thirdparty/opus/celt/mathops.c
	SRC += src/thirdparty/opus/celt/mdct.c
	SRC += src/thirdparty/opus/celt/modes.c
	SRC += src/thirdparty/opus/celt/pitch.c
	SRC += src/thirdparty/opus/celt/celt_lpc.c
	SRC += src/thirdparty/opus/celt/quant_bands.c
	SRC += src/thirdparty/opus/celt/rate.c
	SRC += src/thirdparty/opus/celt/vq.c
	SRC += src/thirdparty/opus/silk/CNG.c
	SRC += src/thirdparty/opus/silk/code_signs.c
	SRC += src/thirdparty/opus/silk/init_decoder.c
	SRC += src/thirdparty/opus/silk/decode_core.c
	SRC += src/thirdparty/opus/silk/decode_frame.c
	SRC += src/thirdparty/opus/silk/decode_parameters.c
	SRC += src/thirdparty/opus/silk/decode_indices.c
	SRC += src/thirdparty/opus/silk/decode_pulses.c
	SRC += src/thirdparty/opus/silk/decoder_set_fs.c
	SRC += src/thirdparty/opus/silk/dec_API.c
	SRC += src/thirdparty/opus/silk/enc_API.c
	SRC += src/thirdparty/opus/silk/encode_indices.c
	SRC += src/thirdparty/opus/silk/encode_pulses.c
	SRC += src/thirdparty/opus/silk/gain_quant.c
	SRC += src/thirdparty/opus/silk/interpolate.c
	SRC += src/thirdparty/opus/silk/LP_variable_cutoff.c
	SRC += src/thirdparty/opus/silk/NLSF_decode.c
	SRC += src/thirdparty/opus/silk/NSQ.c
	SRC += src/thirdparty/opus/silk/NSQ_del_dec.c
	SRC += src/thirdparty/opus/silk/PLC.c
	SRC += src/thirdparty/opus/silk/shell_coder.c
	SRC += src/thirdparty/opus/silk/tables_gain.c
	SRC += src/thirdparty/opus/silk/tables_LTP.c
	SRC += src/thirdparty/opus/silk/tables_NLSF_CB_NB_MB.c
	SRC += src/thirdparty/opus/silk/tables_NLSF_CB_WB.c
	SRC += src/thirdparty/opus/silk/tables_other.c
	SRC += src/thirdparty/opus/silk/tables_pitch_lag.c
	SRC += src/thirdparty/opus/silk/tables_pulses_per_block.c
	SRC += src/thirdparty/opus/silk/VAD.c
	SRC += src/thirdparty/opus/silk/control_audio_bandwidth.c
	SRC += src/thirdparty/opus/silk/quant_LTP_gains.c
	SRC += src/thirdparty/opus/silk/VQ_WMat_EC.c
	SRC += src/thirdparty/opus/silk/HP_variable_cutoff.c
	SRC += src/thirdparty/opus/silk/NLSF_encode.c
	SRC += src/thirdparty/opus/silk/NLSF_VQ.c
	SRC += src/thirdparty/opus/silk/NLSF_unpack.c
	SRC += src/thirdparty/opus/silk/NLSF_del_dec_quant.c
	SRC += src/thirdparty/opus/silk/process_NLSFs.c
	SRC += src/thirdparty/opus/silk/stereo_LR_to_MS.c
	SRC += src/thirdparty/opus/silk/stereo_MS_to_LR.c
	SRC += src/thirdparty/opus/silk/check_control_input.c
	SRC += src/thirdparty/opus/silk/control_SNR.c
	SRC += src/thirdparty/opus/silk/init_encoder.c
	SRC += src/thirdparty/opus/silk/control_codec.c
	SRC += src/thirdparty/opus/silk/A2NLSF.c
	SRC += src/thirdparty/opus/silk/ana_filt_bank_1.c
	SRC += src/thirdparty/opus/silk/biquad_alt.c
	SRC += src/thirdparty/opus/silk/bwexpander_32.c
	SRC += src/thirdparty/opus/silk/bwexpander.c
	SRC += src/thirdparty/opus/silk/debug.c
	SRC += src/thirdparty/opus/silk/decode_pitch.c
	SRC += src/thirdparty/opus/silk/inner_prod_aligned.c
	SRC += src/thirdparty/opus/silk/lin2log.c
	SRC += src/thirdparty/opus/silk/log2lin.c
	SRC += src/thirdparty/opus/silk/LPC_analysis_filter.c
	SRC += src/thirdparty/opus/silk/LPC_inv_pred_gain.c
	SRC += src/thirdparty/opus/silk/table_LSF_cos.c
	SRC += src/thirdparty/opus/silk/NLSF2A.c
	SRC += src/thirdparty/opus/silk/NLSF_stabilize.c
	SRC += src/thirdparty/opus/silk/NLSF_VQ_weights_laroia.c
	SRC += src/thirdparty/opus/silk/pitch_est_tables.c
	SRC += src/thirdparty/opus/silk/resampler.c
	SRC += src/thirdparty/opus/silk/resampler_down2_3.c
	SRC += src/thirdparty/opus/silk/resampler_down2.c
	SRC += src/thirdparty/opus/silk/resampler_private_AR2.c
	SRC += src/thirdparty/opus/silk/resampler_private_down_FIR.c
	SRC += src/thirdparty/opus/silk/resampler_private_IIR_FIR.c
	SRC += src/thirdparty/opus/silk/resampler_private_up2_HQ.c
	SRC += src/thirdparty/opus/silk/resampler_rom.c
	SRC += src/thirdparty/opus/silk/sigm_Q15.c
	SRC += src/thirdparty/opus/silk/sort.c
	SRC += src/thirdparty/opus/silk/sum_sqr_shift.c
	SRC += src/thirdparty/opus/silk/stereo_decode_pred.c
	SRC += src/thirdparty/opus/silk/stereo_encode_pred.c
	SRC += src/thirdparty/opus/silk/stereo_find_predictor.c
	SRC += src/thirdparty/opus/silk/stereo_quant_pred.c
	SRC += src/thirdparty/opus/silk/LPC_fit.c
	SRC += src/thirdparty/opus/silk/float/apply_sine_window_FLP.c
	SRC += src/thirdparty/opus/silk/float/corrMatrix_FLP.c
	SRC += src/thirdparty/opus/silk/float/encode_frame_FLP.c
	SRC += src/thirdparty/opus/silk/float/find_LPC_FLP.c
	SRC += src/thirdparty/opus/silk/float/find_LTP_FLP.c
	SRC += src/thirdparty/opus/silk/float/find_pitch_lags_FLP.c
	SRC += src/thirdparty/opus/silk/float/find_pred_coefs_FLP.c
	SRC += src/thirdparty/opus/silk/float/LPC_analysis_filter_FLP.c
	SRC += src/thirdparty/opus/silk/float/LTP_analysis_filter_FLP.c
	SRC += src/thirdparty/opus/silk/float/LTP_scale_ctrl_FLP.c
	SRC += src/thirdparty/opus/silk/float/noise_shape_analysis_FLP.c
	SRC += src/thirdparty/opus/silk/float/process_gains_FLP.c
	SRC += src/thirdparty/opus/silk/float/regularize_correlations_FLP.c
	SRC += src/thirdparty/opus/silk/float/residual_energy_FLP.c
	SRC += src/thirdparty/opus/silk/float/warped_autocorrelation_FLP.c
	SRC += src/thirdparty/opus/silk/float/wrappers_FLP.c
	SRC += src/thirdparty/opus/silk/float/autocorrelation_FLP.c
	SRC += src/thirdparty/opus/silk/float/burg_modified_FLP.c
	SRC += src/thirdparty/opus/silk/float/bwexpander_FLP.c
	SRC += src/thirdparty/opus/silk/float/energy_FLP.c
	SRC += src/thirdparty/opus/silk/float/inner_product_FLP.c
	SRC += src/thirdparty/opus/silk/float/k2a_FLP.c
	SRC += src/thirdparty/opus/silk/float/LPC_inv_pred_gain_FLP.c
	SRC += src/thirdparty/opus/silk/float/pitch_analysis_core_FLP.c
	SRC += src/thirdparty/opus/silk/float/scale_copy_vector_FLP.c
	SRC += src/thirdparty/opus/silk/float/scale_vector_FLP.c
	SRC += src/thirdparty/opus/silk/float/schur_FLP.c
	SRC += src/thirdparty/opus/silk/float/sort_FLP.c
	ifeq ($(OPUS_DEC),1)
		SRC += src/thirdparty/opusfile/src/info.c
		SRC += src/thirdparty/opusfile/src/internal.c
		SRC += src/thirdparty/opusfile/src/opusfile.c
		SRC += src/thirdparty/opusfile/src/stream.c
	endif
endif

ifeq ($(OGG_SUPPORT),1)
	INC_PATH	+= -Isrc/thirdparty/libogg/include
	BAE_FLAGS	+= -DSUPPORT_OGG_FORMAT=1
endif

ifeq ($(LZMA_SUPPORT),1)
	BAE_FLAGS += -DUSE_LZMA_COMPRESSION=1
	BAE_FLAGS += -DZ7_ST
	INC_PATH += -Isrc/thirdparty/lzma-26.00/C
	SRC += src/BAE_Source/Common/X_LZMA.c
	SRC += src/thirdparty/lzma-26.00/C/Alloc.c
	SRC += src/thirdparty/lzma-26.00/C/7zAlloc.c
	SRC += src/thirdparty/lzma-26.00/C/7zCrc.c
	SRC += src/thirdparty/lzma-26.00/C/7zCrcOpt.c
	SRC += src/thirdparty/lzma-26.00/C/7zStream.c
	SRC += src/thirdparty/lzma-26.00/C/XzCrc64.c
	SRC += src/thirdparty/lzma-26.00/C/XzCrc64Opt.c
	SRC += src/thirdparty/lzma-26.00/C/Sha256.c
	SRC += src/thirdparty/lzma-26.00/C/Sha256Opt.c
	SRC += src/thirdparty/lzma-26.00/C/CpuArch.c
	SRC += src/thirdparty/lzma-26.00/C/Bra.c
	SRC += src/thirdparty/lzma-26.00/C/Bra86.c
	SRC += src/thirdparty/lzma-26.00/C/BraIA64.c
	SRC += src/thirdparty/lzma-26.00/C/Delta.c
	SRC += src/thirdparty/lzma-26.00/C/LzmaDec.c
	SRC += src/thirdparty/lzma-26.00/C/Lzma2Dec.c
	SRC += src/thirdparty/lzma-26.00/C/LzFind.c
	SRC += src/thirdparty/lzma-26.00/C/LzmaEnc.c
	SRC += src/thirdparty/lzma-26.00/C/Lzma2Enc.c
	SRC += src/thirdparty/lzma-26.00/C/Xz.c
	SRC += src/thirdparty/lzma-26.00/C/XzDec.c
endif

ifeq ($(MOD2RMF),1)
	# libNeoBAE srcs + split mod2rmf sources
	SRC += src/mod2rmf/mod2rmf_common.c src/mod2rmf/mod2rmf_encoder.c src/mod2rmf/mod2rmf_resampler.c src/mod2rmf/mod2rmf_rmfcreat.c src/mod2rmf/mod2rmf_song.c
	INC_PATH += -Isrc/mod2rmf
	INC_PATH += -Isrc/thirdparty/libxmp/include
	BAE_FLAGS += -DLIBXMP_STATIC=1 -DLIBXMP_CORE_PLAYER=1 -DLIBXMP_BUILD=1
	SRC += src/thirdparty/libxmp/src/lite/lite-virtual.c
	SRC += src/thirdparty/libxmp/src/lite/lite-format.c
	SRC += src/thirdparty/libxmp/src/lite/lite-period.c
	SRC += src/thirdparty/libxmp/src/lite/lite-player.c
	SRC += src/thirdparty/libxmp/src/lite/lite-read_event.c
	SRC += src/thirdparty/libxmp/src/lite/lite-misc.c
	SRC += src/thirdparty/libxmp/src/lite/lite-dataio.c
	SRC += src/thirdparty/libxmp/src/lite/lite-lfo.c
	SRC += src/thirdparty/libxmp/src/lite/lite-scan.c
	SRC += src/thirdparty/libxmp/src/lite/lite-control.c
	SRC += src/thirdparty/libxmp/src/lite/lite-filter.c
	SRC += src/thirdparty/libxmp/src/lite/lite-effects.c
	SRC += src/thirdparty/libxmp/src/lite/lite-mixer.c
	SRC += src/thirdparty/libxmp/src/lite/lite-mix_all.c
	SRC += src/thirdparty/libxmp/src/lite/lite-load_helpers.c
	SRC += src/thirdparty/libxmp/src/lite/lite-load.c
	SRC += src/thirdparty/libxmp/src/lite/lite-filetype.c
	SRC += src/thirdparty/libxmp/src/lite/lite-hio.c
	SRC += src/thirdparty/libxmp/src/lite/lite-smix.c
	SRC += src/thirdparty/libxmp/src/lite/lite-memio.c
	SRC += src/thirdparty/libxmp/src/lite/lite-rng.c
	SRC += src/thirdparty/libxmp/src/lite/lite-win32.c
	SRC += src/thirdparty/libxmp/src/lite/lite-flow.c
	SRC += src/thirdparty/libxmp/src/lite/lite-common.c
	SRC += src/thirdparty/libxmp/src/lite/lite-itsex.c
	SRC += src/thirdparty/libxmp/src/lite/lite-sample.c
	SRC += src/thirdparty/libxmp/src/lite/lite-xm_load.c
	SRC += src/thirdparty/libxmp/src/lite/lite-mod_load.c
	SRC += src/thirdparty/libxmp/src/lite/lite-s3m_load.c
	SRC += src/thirdparty/libxmp/src/lite/lite-it_load.c
endif

ifeq ($(SONGTOOL),1)
	# songtool uses shared codec parsing/resolution helpers
	SRC += src/mod2rmf/mod2rmf_encoder.c
	INC_PATH += -Isrc/mod2rmf
endif

# Nested ifeq from hell!

ifeq ($(BUILD_GUI),1)
	BAE_FLAGS += -D_ZEFI_GUI=1
	SRC	+= src/gui/gui_theme.c \
		src/gui/gui_widgets.c \
		src/gui/gui_text.c \
		src/gui/gui_midi_vkbd.c \
		src/gui/gui_export.c \
		src/gui/gui_dialogs.c \
		src/gui/gui_bae.c \
		src/gui/gui_settings.c \
		src/gui/gui_panels.c \
		src/gui/gui_main.c
	
	# Add debug console for DEBUG builds
	ifeq ($(DEBUG),1)
		SRC += src/gui/gui_debug_console.c
	endif
else
	ifeq ($(RMFINFO),1)
		# libNeoBAE srcs + rmfinfo.c
		SRC += src/rmfinfo/rmfinfo.c
	else
		ifeq ($(INSTDUMP),1)
			# libNeoBAE srcs + instdump.c
			SRC += src/rmfinfo/instdump.c
		else
			ifeq ($(RMF2MID),1)
				# libNeoBAE srcs + rmf2mid.c
				SRC += src/rmf2mid/rmf2mid.c
			else
				ifeq ($(MID2RMF),1)
					# libNeoBAE srcs + mid2rmf.c
					SRC += src/mid2rmf/mid2rmf.c
				else
					ifeq ($(MID2RMI),1)
						# libNeoBAE srcs + mid2rmi.c
						SRC += src/mid2rmi/mid2rmi.c
					else
						ifeq ($(MOD2RMF_APP),1)
							SRC += src/mod2rmf/mod2rmf_main.c
						else
							ifeq ($(BANKRECOMP),1)
								# libNeoBAE srcs + bankrecomp_api.c
								SRC += src/bankrecomp/bankrecomp_api.c
							else
								ifeq ($(SF2_TO_HSB),1)
									# libNeoBAE srcs + sf2-hsb
									SRC += src/sf2-hsb/sf2_hsb_converter.c \
										src/mod2rmf/mod2rmf_encoder.c \
										src/sf2-hsb/sf2_parser.c \
										src/sf2-hsb/hsb_writer.c \
										src/sf2-hsb/sf2_hsb_main.c
									BAE_FLAGS += -Isrc/mod2rmf
								else							
									ifeq ($(NBSTUDIO),1)
										SRC += 	src/nbstudio/editor_main.cpp \
											src/nbstudio/editor_bank.cpp \
											src/nbstudio/editor_instrument_ext_dialog.cpp \
											src/nbstudio/editor_metadata_dialog.cpp \
											src/nbstudio/editor_pianoroll_panel.cpp \
											src/nbstudio/batch_compress_dialog.cpp
										ifneq ($(MACOSX),1)
											BAE_FLAGS += $(shell pkg-config --cflags gtk+-3.0) $(shell pkg-config --cflags glib-2.0)
											BAE_LIBS += -lz $(shell pkg-config --libs gtk+-3.0) $(shell pkg-config --libs glib-2.0)
										endif
									else
										ifeq ($(NBEDITOR),1)
											SRC += src/nbeditor/nbeditor_main.cpp \
												src/thirdparty/imgui/imgui.cpp \
												src/thirdparty/imgui/imgui_draw.cpp \
												src/thirdparty/imgui/imgui_tables.cpp \
												src/thirdparty/imgui/imgui_widgets.cpp \
												src/thirdparty/imgui/backends/imgui_impl_sdl3.cpp \
												src/thirdparty/imgui/backends/imgui_impl_sdlrenderer3.cpp
											INC_PATH += -Isrc/thirdparty/imgui -Isrc/thirdparty/imgui/backends
										else
											ifeq ($(ADP2WAV),1)
												# adp2wav with third-party G.722 decoder
												SRC := src/adp2wav/adp2wav_main.c src/adp2wav/adp2wav_decode.c src/thirdparty/libg722/g722_decode.c
											else
												ifeq ($(MIDDECOMP),1)
													SRC := src/mthc/mthc_decomp.c src/mthc/mthc_main.c
												else
													ifeq ($(RAYLIB_EXAMPLE),1)
														SRC += src/raylib_example/audio_stream_callback.c
														BAE_LIBS += -lraylib -lm
													else
														ifneq ($(WASM),1)
															ifneq ($(SONGTOOL),1)
																	ifeq ($(RINGTONE2MID),1)
																		# libNeoBAE srcs + ringtone2mid.c
																		SRC += src/ringtone2mid/ringtone2mid.c
																	else
																		ifeq ($(NEOBAE_TUI),1)
																			# neobae-tui = libNeoBAE srcs + neobae_tui.c
																			SRC += src/playbae/neobae_tui.c
																		else
																			# playbae = libNeoBAE srcs + playbae.c
																			SRC += src/playbae/playbae.c
																		endif
																	endif
																else
																	# libNeoBAE srcs + songtool.c
																	SRC += src/songtool/songtool.c
																endif
															endif
														endif
													endif
												endif
											endif
										endif
									endif
								endif
							endif
						endif
					endif
				endif
			endif
		endif
	endif

ifeq ($(MTHC_SUPPORT),1)
	ifneq ($(MIDDECOMP),1)
		ifneq ($(ADP2WAV),1)
			SRC += src/mthc/mthc_decomp.c
			BAE_FLAGS += -DUSE_MTHC_SUPPORT=1
		endif
	endif
endif

ifeq ($(ADP_SUPPORT),1)
	ifneq ($(ADP2WAV),1)
		SRC += src/adp2wav/adp2wav_decode.c \
			src/thirdparty/libg722/g722_decode.c
		BAE_FLAGS += -DUSE_ADP_SUPPORT=1
	endif
endif


ifeq ($(QOA_SUPPORT),1)
	BAE_FLAGS += -DUSE_QOA_SUPPORT=1
	INC_PATH += -Isrc/thirdparty/qoa
	SRC += src/BAE_Source/Common/XQOAFiles.c
endif

ifeq ($(KARAOKE),1)
	ifneq ($(BUILD_GUI),)
		SRC += src/gui/gui_karaoke.c
	endif
endif

ifeq ($(ENABLE_MIDI_HW),1)
	ifneq ($(BUILD_GUI),)
		# RtMidi (C wrapper) - provide real-time MIDI input for GUI
		BAE_FLAGS += -DSUPPORT_MIDI_HW=1
		SRC +=  src/gui/gui_midi_hw.c \
			src/gui/gui_midi_hw_input.c \
			src/gui/gui_midi_hw_output.c \
			src/thirdparty/rtmidi/rtmidi_c.cpp \
			src/thirdparty/rtmidi/RtMidi.cpp
	endif
endif

ifeq ($(PLAYLIST),1)
	ifneq ($(BUILD_GUI),)
		BAE_FLAGS += -DSUPPORT_PLAYLIST=1
		SRC +=  src/gui/gui_playlist.c
	endif
endif


ifeq ($(LOGFILE),1)
	BAE_FLAGS += -DOUTPUT_TO_LOGFILE=1
endif

ifeq ($(WINDOWS),1)
	ifneq ($(filter 1,$(FLAC_DEC) $(FLAC_ENC)),)
		INC_PATH += -Isrc/thirdparty/flac/src/share/win_utf8_io
		BAE_FLAGS += -DFLAC__NO_DLL
		SRC += src/thirdparty/flac/src/share/win_utf8_io/win_utf8_io.c
	endif
endif

ifeq ($(KARAOKE),1)
	BAE_FLAGS += -DSUPPORT_KARAOKE=1
endif

ifeq ($(BAESCRIPT),1)
	BAE_FLAGS += -DSUPPORT_BAESCRIPT=1
	INC_PATH += -Isrc/script
	SRC += src/script/baescript.c \
		src/script/baescript_lexer.c \
		src/script/baescript_parser.c \
		src/script/baescript_vm.c
	ifneq ($(BUILD_GUI),)
		SRC += src/gui/gui_script_editor.c
	endif
endif

OBJ_DIR 	:= $(BUILD_DIR)obj/
# Create unique object names for conflicting basenames across third-party trees.
define uniq_obj_src
$(subst src/thirdparty/opus/celt/mdct.c,src/thirdparty/opus/celt/opus_mdct.c,$(subst src/thirdparty/flac/src/libFLAC/lpc.c,src/thirdparty/flac/src/libFLAC/flac_lpc.c,$(subst src/thirdparty/flac/src/libFLAC/window.c,src/thirdparty/flac/src/libFLAC/flac_window.c,$(subst src/thirdparty/libvorbis/lib/lpc.c,src/thirdparty/libvorbis/lib/vorbis_lpc.c,$(subst src/thirdparty/libvorbis/lib/window.c,src/thirdparty/libvorbis/lib/vorbis_window.c,$(subst src/thirdparty/opus/src/analysis.c,src/thirdparty/opus/src/opus_analysis.c,$(subst src/thirdparty/opusfile/src/info.c,src/thirdparty/opusfile/src/opusfile_info.c,$(subst src/thirdparty/opusfile/src/stream.c,src/thirdparty/opusfile/src/opusfile_stream.c,$(1)))))))))
endef

define obj_name_from_src
$(notdir $(basename $(call uniq_obj_src,$(1))))
endef

SRC_UNIQUE := $(foreach s,$(SRC),$(call uniq_obj_src,$(s)))
SRC_BIN_UNIQUE := $(foreach s,$(SRC),$(call uniq_obj_src,$(s)))
OBJ_BIN 	:= $(addprefix $(OBJ_DIR),$(addsuffix .o,$(notdir $(basename $(SRC_BIN_UNIQUE)))))

ifeq ($(BUILD_GUI),1)

BAE_FLAGS += -D_ZEFI_GUI=1

# If EMBED_TTF_FONT specified, generate embedded_font.h and define EMBED_TTF_FONT
ifeq ($(EMBED_FONT),1)
ifdef EMBED_TTF_FONT
BAE_FLAGS += -DEMBED_TTF_FONT -I$(OBJ_DIR)

EMBED_FONT_HEADER := $(OBJ_DIR)embedded_font.h
$(EMBED_FONT_HEADER): $(EMBED_TTF_FONT) ../scripts/create_embedded_font_h.py
	@echo @embed $<
	@mkdir -p $(dir $(EMBED_FONT_HEADER))
	@python3 ../scripts/create_embedded_font_h.py $(EMBED_TTF_FONT) $(EMBED_FONT_HEADER)

$(OBJ_DIR)gui_main.o: $(EMBED_FONT_HEADER)
endif # EMBED_FONT_HEADER
endif # EMBED_FONT

endif # BUILD_GUI

# If EMBED_PATCH_FILE specified, generate BAEPatches.h that embeds the binary bank
ifeq ($(EMBED_PATCHES),1)
ifdef EMBED_PATCH_FILE
BAE_FLAGS += -D_BUILT_IN_PATCHES=1 -I$(OBJ_DIR)

EMBED_PATCH_HEADER := $(OBJ_DIR)BAEPatches.h
$(EMBED_PATCH_HEADER): $(EMBED_PATCH_FILE) ../scripts/create_embedded_patches_h.py
	@echo @embed $<
	@mkdir -p $(dir $(EMBED_PATCH_HEADER))
	@python3 ../scripts/create_embedded_patches_h.py $(EMBED_PATCH_FILE) $(EMBED_PATCH_HEADER)
$(OBJ_DIR)NeoBAE.o: $(EMBED_PATCH_HEADER)

ifeq ($(USE_BUILTIN_PATCHES_WITH_SF2),1)
BAE_FLAGS += -D_LOAD_BUILTIN_PATCHES_FOR_SF2=1
endif # USE_BUILTIN_PATCHES_WITH_SF2

ifeq ($(USE_BUILTIN_PATCHES_WITH_DLS),1)
BAE_FLAGS += -D_LOAD_BUILTIN_PATCHES_FOR_DLS=1
endif # USE_BUILTIN_PATCHES_WITH_DLS

endif # EMBED_PATCH_FILE
endif # EMBED_PATCHES

# Rules for compiling source files to object files
# Create a function to map source files to object files with unique names for conflicts
define make_obj_rule
$(OBJ_DIR)$(call obj_name_from_src,$(1)).o: $(1)
	@echo @compile $$<
	@mkdir -p $(OBJ_DIR)
	$(SILENT)$(if $(filter %.cpp,$(1)),${CXX} -c ${CXXFLAGS},${CC} -c ${CFLAGS}) $$< -o $$@
endef

ifeq ($(USE_SDL3),1)
	BAE_FLAGS += -D_USING_SDL3=1
endif
ifeq ($(USE_RAYLIB),1)
	BAE_FLAGS += -D_USING_RAYLIB=1
endif
#### End Makefile.common
