# Built-in Patches (affects entire NeoBAE library)
# Must be an HSB bank, leave empty to disable built-in patches completely
EMBED_PATCH_FILE := src/banks/patches111/patches111.hsb

# TTF Font (for zefidi GUI)
# Not required but severely recommended
EMBED_TTF_FONT := src/thirdparty/fonts/HelveticaNeue.ttf

### It is probably best not to change anything below this line, unless absolutely necessary for your environment

BUILD_DIR	  := build/
TEST_OUT_DIR  := tests/
TARGET_OUT	  := bin/
BAE_FLAGS	  :=
BAE_LD_FLAGS  :=
BAE_LIBS      :=
.DEFAULT_GOAL := all
LZMA_VERS := 5.8.2

# Default build options (override with NOAUTO=1)
ifneq ($(WASM),1)
	ifneq ($(NOAUTO),1)
		ZMF_SUPPORT := 1
		KARAOKE := 1
		BAESCRIPT := 1
		PLAYLIST := 1
		SF2_SUPPORT := 1
		USE_FLUIDSYNTH := 1
		EMBED_PATCHES := 1
		EMBED_FONT := 1
		XMF_SUPPORT := 1
		DISABLE_NOKIA := 0			    
		DISABLE_BEATNIK_SF2_NRPN := 0
		FIX_SPAN_DC := 1
		CLASSIC_CHORUS := 1
		LZMA_SUPPORT := 1
		CREATION_API := 0
	endif
endif

ifeq ($(NBSTUDIO),1)
	# NBStudio requires ZMF support
	# and the creation API
	ZMF_SUPPORT := 1
	CREATION_API := 1
	FIX_SPAN_DC := 1
	CLASSIC_CHORUS := 1
endif

ifneq ($(filter 1,$(ZMF_SUPPORT) $(CREATION_API)),) 
	# All of these are required for ZMF support
	OGG_SUPPORT := 1
	MP3_DEC := 1
	MP3_ENC := 1
	FLAC_DEC := 1
	FLAC_ENC := 1
	VORBIS_DEC := 1
	VORBIS_ENC := 1
	OPUS_DEC := 1
	OPUS_ENC := 1
	LZMA_SUPPORT := 1
	FIX_SPAN_DC := 1
	CLASSIC_CHORUS := 1
endif

# Disable SDL2 if using SDL3
ifeq ($(USE_SDL3),1)
	USE_SDL2 := 0
endif

# Likewise, Disable SDL3 if using SDL2
ifeq ($(USE_SDL2),1)
	USE_SDL3 := 0
endif

# We only support FluidSynth for SF2 now
ifeq ($(SF2_SUPPORT),1)
	USE_FLUIDSYNTH := 1
endif

# In case we support other synths again
ifneq ($(USE_FLUIDSYNTH),1)
	XMF_SUPPORT := 0
endif

# Force OGG support if VORBIS is chosen
ifneq ($(OGG_SUPPORT),1)
	ifneq ($(filter 1,$(VORBIS_ENC) $(VORBIS_DEC) $(FLAC_DEC) $(FLAC_ENC) $(OPUS_DEC) $(OPUS_ENC)),) 
		OGG_SUPPORT := 1
	endif
endif

ifneq ($(filter 1,$(VERBOSE) $(V)),)
	SILENT :=
else
	SILENT := @
endif

# Begin Allow Overrides
ifeq ($(TARGET_LIB),)
	TARGET_LIB	:= libNeoBAE
endif

ifeq ($(TARGET_BIN),)
	ifneq ($(BUILD_GUI),) 
		TARGET_BIN	:= zefidi
		TARGET_NAME := $(TARGET_BIN)
	else
		TARGET_BIN	:= playbae
		TARGET_NAME := $(TARGET_BIN)
	endif
else
	TARGET_NAME := $(TARGET_BIN)	
endif

ifeq ($(TEST_BIN_PREFIX),)
	TEST_BIN	:= $(TARGET_OUT)$(TARGET_BIN)
else
	TEST_BIN	:= $(TEST_BIN_PREFIX)$(TARGET_OUT)$(TARGET_BIN)
endif
# End Allow Overrides

INC_PATH	:= -Isrc/BAE_Source/Common
INC_PATH	+= -Isrc/BAE_Source/Platform
INC_PATH	+= -Isrc/thirdparty/config

ifneq ($(filter 1,$(MP3_ENC) $(MP3_DEC)),) 
	INC_PATH  += -Isrc/BAE_MPEG_Source_II
endif

ifeq ($(MP3_DEC),1)
INC_PATH	+= -Isrc/thirdparty/minimp3
endif

ifeq ($(ENABLE_MIDI_HW),1)
INC_PATH	+= -Isrc/thirdparty/rtmidi
endif

ifeq ($(DISABLE_NOKIA),1)
	BAE_FLAGS += -DDISABLE_NOKIA_PATCH=1
endif

ifeq ($(DISABLE_BEATNIK_SF2_NRPN),1)
	BAE_FLAGS += -DISABLE_BEATNIK_SF2_NRPN=1
endif

ifeq ($(FIX_SPAN_DC),1)
	BAE_FLAGS += -DBAE_FIX_SPAN_DC=1
endif

ifeq ($(CLASSIC_CHORUS),1)
	BAE_FLAGS += -DBAE_CLASSIC_CHORUS=1
endif

ifeq ($(ZMF_SUPPORT),1)
	BAE_FLAGS += -DUSE_ZMF_SUPPORT=1
endif

ifneq ($(filter 1,$(FLAC_ENC) $(FLAC_DEC)),) 
	INC_PATH	+= -Isrc/thirdparty/flac/include -Isrc/thirdparty/flac/src/libFLAC/include
	ifeq ($(XPHACK),1)
		BAE_LIBS := -lFLAC.dll -lpthread $(BAE_LIBS)
	else
		BAE_LIBS := -lFLAC -lpthread $(BAE_LIBS)
	endif
	BAE_FLAGS += -DHAVE_STDINT_H=1 -DHAVE_INTTYPES_H=1 -DSIZE_T_MAX=SIZE_MAX
	ifeq ($(OGG_SUPPORT),1)
		BAE_FLAGS += -DFLAC__HAS_OGG=1
	else
		BAE_FLAGS += -DFLAC__HAS_OGG=0
	endif
endif

ifneq ($(filter 1,$(OPUS_DEC) $(OPUS_ENC)),)
	INC_PATH	+= -Isrc/thirdparty/opus/include
	ifeq ($(OPUS_DEC),1)
		INC_PATH	+= -Isrc/thirdparty/opusfile/include
	endif
	ifeq ($(XPHACK),1)
		BAE_LIBS 	:= -lopus.dll $(BAE_LIBS)
		ifeq ($(OPUS_DEC),1)
			BAE_LIBS 	:= -lopusfile.dll $(BAE_LIBS)
		endif
	else
		BAE_LIBS 	:= -lopus $(BAE_LIBS)
		ifeq ($(OPUS_DEC),1)
			BAE_LIBS 	:= -lopusfile $(BAE_LIBS)
		endif
	endif
	ifeq ($(OPUS_DEC),1)
		BAE_FLAGS += -DUSE_OPUS_DECODER=1
	endif
	ifeq ($(OPUS_ENC),1)
		BAE_FLAGS += -DUSE_OPUS_ENCODER=1
	endif
endif

ifneq ($(filter 1,$(VORBIS_DEC) $(VORBIS_ENC)),) 
	INC_PATH	+= -Isrc/thirdparty/libvorbis/include -Isrc/thirdparty/libvorbis/lib
	ifneq ($(filter 1,$(VORBIS_ENC)),)
		ifeq ($(XPHACK),1)
			BAE_LIBS := -lvorbisenc.dll $(BAE_LIBS)
		else
			BAE_LIBS := -lvorbisenc $(BAE_LIBS)
		endif
	endif
	ifeq ($(XPHACK),1)
		BAE_LIBS := -lvorbisfile.dll -lvorbis.dll $(BAE_LIBS)
	else
		BAE_LIBS := -lvorbisfile -lvorbis $(BAE_LIBS)
	endif
endif

# default to ANSI
ifeq ($(BAE_API),)
	BAE_API		:= Ansi
endif

## Begin Easy API -> X_PLATFORM
# Supported APIs
ifeq ($(BAE_API),Ansi)
	# No audio output
	BAE_FLAGS += 	-DX_PLATFORM=X_ANSI
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),WASM)
	BAE_FLAGS += 	-DX_PLATFORM=X_WASM
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c \
					src/BAE_Source/Platform/BAE_API_WASM_Export.c
endif
ifeq ($(BAE_API),WinOS)
	BAE_FLAGS += 	-DX_PLATFORM=X_WIN95
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c \
			src/BAE_Source/Platform/BAE_API_$(BAE_API)_Capture.c \
			src/BAE_Source/Platform/BAE_API_$(BAE_API)_Thread.c
endif
ifeq ($(BAE_API),SDL2)
	BAE_FLAGS += 	-DX_PLATFORM=X_SDL2 -DUSE_SDL2=1
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),SDL3)
	BAE_FLAGS += 	-DX_PLATFORM=X_SDL3
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif


# zefie has not tested these APIs
ifeq ($(BAE_API),MacOSX)
	BAE_FLAGS += 	-DX_PLATFORM=X_MACINTOSH
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),Android)
	BAE_FLAGS += 	-DX_PLATFORM=X_ANDROID
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
ifeq ($(BAE_API),IOS)
	BAE_FLAGS += 	-DX_PLATFORM=X_IOS
	SRC       :=	src/BAE_Source/Platform/BAE_API_$(BAE_API).c
endif
## End Easy API -> X_PLATFORM
### End configure BAE API

# Debug
ifeq ($(DEBUG),1)
	BAE_FLAGS +=    -D_DEBUG=1 -Wall -Wno-unused-function
	# Add debug callback stub for library
	SRC += src/BAE_Source/Common/X_DebugCallback.c
endif


ifeq ($(SF2_SUPPORT),1)
	BAE_FLAGS += -DUSE_SF2_SUPPORT=1
endif

ifeq ($(XMF_SUPPORT),1)
	BAE_FLAGS += -DUSE_XMF_SUPPORT=1
	SRC += src/BAE_Source/Common/GenXMF.c
	BAE_LIBS += -lz
endif


# Primary libNeoBAE sources
SRC		+=	src/BAE_Source/Common/DriverTools.c \
			src/BAE_Source/Common/GenAudioStreams.c \
			src/BAE_Source/Common/GenCache.c \
			src/BAE_Source/Common/GenChorus.c \
			src/BAE_Source/Common/GenFiltersReverbU3232.c \
			src/BAE_Source/Common/GenInterp2ReverbU3232.c \
			src/BAE_Source/Common/GenOutput.c \
			src/BAE_Source/Common/GenPatch.c \
			src/BAE_Source/Common/GenReverb.c \
			src/BAE_Source/Common/GenReverbNew.c \
			src/BAE_Source/Common/GenReverbNeo.c \
			src/BAE_Source/Common/GenRMI.c \
			src/BAE_Source/Common/GenSample.c \
			src/BAE_Source/Common/GenSeq.c \
			src/BAE_Source/Common/GenSeqTools.c \
			src/BAE_Source/Common/GenSetup.c \
			src/BAE_Source/Common/GenSong.c \
			src/BAE_Source/Common/GenSoundFiles.c \
			src/BAE_Source/Common/GenSynth.c \
			src/BAE_Source/Common/GenSynthFiltersSimple.c \
			src/BAE_Source/Common/GenSynthFiltersU3232.c \
			src/BAE_Source/Common/GenSynthInterp2Simple.c \
			src/BAE_Source/Common/GenSynthInterp2U3232.c \
			src/BAE_Source/Common/NeoBAE.c \
			src/BAE_Source/Common/NewNewLZSS.c \
			src/BAE_Source/Common/SampleTools.c \
			src/BAE_Source/Common/X_API.c \
			src/BAE_Source/Common/X_Decompress.c \
			src/BAE_Source/Common/X_IMA.c \
			src/BAE_Source/Common/g711.c \
			src/BAE_Source/Common/g721.c \
			src/BAE_Source/Common/g723_24.c \
			src/BAE_Source/Common/g723_40.c \
			src/BAE_Source/Common/g72x.c \
			src/BAE_Source/Common/sha1mini.c \
			src/BAE_Source/Common/XFileTypes.c

ifeq ($(SF2_SUPPORT),1)
	ifeq ($(USE_FLUIDSYNTH),1)
		SRC += src/BAE_Source/Common/GenSF2_FluidSynth.c
		BAE_FLAGS += -D_USING_FLUIDSYNTH=1 
		ifeq ($(WINDOWS),1)					
			ifeq ($(BITS),32)
				INC_PATH += -I../deps/win/FluidSynth/i686-w64-mingw32/include
				BAE_LD_FLAGS += -L../deps/win/FluidSynth/i686-w64-mingw32/lib/
				BAE_LIBS += ../deps/win/FluidSynth/i686-w64-mingw32/lib/libfluidsynth-3.dll.a -Wl,-rpath,'$$ORIGIN'
			else
				INC_PATH += -I../deps/win/FluidSynth/x86_64-w64-mingw32/include
				BAE_LD_FLAGS += -L../deps/win/FluidSynth/x86_64-w64-mingw32/lib/
				BAE_LIBS += ../deps/win/FluidSynth/x86_64-w64-mingw32/lib/libfluidsynth-3.dll.a -Wl,-rpath,'$$ORIGIN'
			endif			
		else
			ifneq ($(XPHACK),1)
				ifneq ($(WASM),1)
					UNAME_S:=$(shell uname -s 2>/dev/null)
					# System FluidSynth for Linux (dynamic) if pkg-config available
					FLUIDSYNTH_CFLAGS := $(shell pkg-config --cflags fluidsynth 2>/dev/null)
					FLUIDSYNTH_LIBS   := $(shell pkg-config --libs fluidsynth 2>/dev/null)
					ifneq ($(FLUIDSYNTH_LIBS),)
						BAE_FLAGS += $(FLUIDSYNTH_CFLAGS)
						# Prepend pkg-config libs; they already have -lfluidsynth and any needed deps
						BAE_LIBS := $(FLUIDSYNTH_LIBS) $(filter-out -lfluidsynth,$(BAE_LIBS))
						ifneq (,$(findstring -static,$(ARCH)))
							ARCH := $(filter-out -static,$(ARCH))
							LDFLAGS := $(filter-out -static,$(LDFLAGS))
						endif
					else
						# Fallback minimal guess
						BAE_FLAGS += -I/usr/include/fluidsynth
						BAE_LIBS += -lfluidsynth $(BAE_LIBS)
					endif
				endif
			endif
		endif
	endif
endif

ifeq ($(MP3_DEC),1)
	# Enable minimp3 wrapper for MPG_* API (decoder only)
	BAE_FLAGS += -DUSE_MINIMP3_WRAPPER=1 -DUSE_MPEG_DECODER=1
	SRC += src/BAE_MPEG_Source_II/XMPEG_minimp3_wrapper.c
endif

# Include XMPEGFilesSun.c when either encoder or decoder is enabled
ifneq ($(filter 1,$(MP3_ENC) $(MP3_DEC)),) 
	SRC += src/BAE_MPEG_Source_II/XMPEGFilesSun.c
endif

# RMF editing and creation API, used by NeoBAE Studio
# This API enables numerous exports in the DLL and LIB
# for interacting with the BAE system
ifeq ($(CREATION_API),1)
	SRC += src/BAE_Source/Common/BAERmfEditor.c
endif

# Optional MP3 encoder integration
# Enable with make MP3_ENC=1 (or set in environment)
# Default to using LAME (MIT-like/GPL licensed) instead of the Helix hmp3
# to avoid problematic licensing. This compiles the bundled LAME sources
# and provides an adapter that implements the legacy MPG_Encode* API.
ifeq ($(MP3_ENC),1)
	ifeq ($(WINDOWS),1)					
		ifeq ($(BITS),32)
			INC_PATH += -I../deps/win/lame/i686-w64-mingw32/include
			BAE_LD_FLAGS += -L../deps/win/lame/i686-w64-mingw32/lib/
			BAE_LIBS += ../deps/win/lame/i686-w64-mingw32/lib/libmp3lame-0.dll.a -Wl,-rpath,'$$ORIGIN'
		else
			INC_PATH += -I../deps/win/lame/x86_64-w64-mingw32/include
			BAE_LD_FLAGS += -L../deps/win/lame/x86_64-w64-mingw32/lib/
			BAE_LIBS += ../deps/win/lame/x86_64-w64-mingw32/lib/libmp3lame-0.dll.a -Wl,-rpath,'$$ORIGIN'
		endif			
	else		
		INC_PATH += $(shell pkg-config --cflags libmp3lame 2>/dev/null)
		LAME_LIBS := $(shell pkg-config --libs libmp3lame 2>/dev/null)
		ifneq ($(LAME_LIBS),)
			BAE_LIBS += $(LAME_LIBS)
		else
			BAE_LIBS += -lmp3lame
		endif
	endif

	BAE_FLAGS += -DUSE_MPEG_ENCODER=1 -DUSE_LAME_ENCODER=1
	SRC += src/BAE_MPEG_Source_II/XMPEG_lame_encoder.cpp
endif

# Add FLAC decoder source files
ifeq ($(FLAC_DEC),1)
	BAE_FLAGS += -DUSE_FLAC_DECODER=1
	# Use shared library instead of compiling sources
endif

# Add FLAC encoder source files  
ifeq ($(FLAC_ENC),1)
	BAE_FLAGS += -DUSE_FLAC_ENCODER=1
	# Use shared library instead of compiling sources
endif

# Add libogg source files
ifeq ($(OGG_SUPPORT),1)
	BAE_FLAGS += -DUSE_OGG_FORMAT=1
	# Use shared library instead of compiling sources
endif

# Add libvorbis decoder source files
ifneq ($(filter 1,$(VORBIS_DEC) $(VORBIS_ENC)),) 
	SRC += src/BAE_Source/Common/XVorbisFiles.c
	ifeq ($(VORBIS_DEC),1)
		BAE_FLAGS += -DUSE_VORBIS_DECODER=1
	endif
	ifeq ($(VORBIS_ENC),1)
		BAE_FLAGS += -DUSE_VORBIS_ENCODER=1
	endif
endif

ifneq ($(filter 1,$(OPUS_DEC) $(OPUS_ENC)),)
	SRC += src/BAE_Source/Common/XOpusFiles.c
endif

ifeq ($(OGG_SUPPORT),1)
	INC_PATH	+= -Isrc/thirdparty/libogg/include
	BAE_FLAGS	+= -DSUPPORT_OGG_FORMAT=1
	ifeq ($(XPHACK),1)
		BAE_LIBS 	+= -logg.dll
	else
		BAE_LIBS 	+= -logg
	endif
endif

ifeq ($(LZMA_SUPPORT),1)
	BAE_FLAGS += -DUSE_LZMA_COMPRESSION=1
	SRC += src/BAE_Source/Common/X_LZMA.c
	ifeq ($(XPHACK),1)
		BAE_LIBS += -llzma.dll
	else
		ifeq ($(WINDOWS),1)
			ifeq ($(BITS),32)
				INC_PATH += -I../deps/win/LZMA-$(LZMA_VERS)/i686-w64-mingw32/include
				BAE_LD_FLAGS += -L../deps/win/LZMA-$(LZMA_VERS)/i686-w64-mingw32/lib/
				BAE_LIBS += ../deps/win/LZMA-$(LZMA_VERS)/i686-w64-mingw32/lib/liblzma-5.dll.a -Wl,-rpath,'$$ORIGIN'
			else
				INC_PATH += -I../deps/win/LZMA-$(LZMA_VERS)/x86_64-w64-mingw32/include
				BAE_LD_FLAGS += -L../deps/win/LZMA-$(LZMA_VERS)/x86_64-w64-mingw32/lib/
				BAE_LIBS += ../deps/win/LZMA-$(LZMA_VERS)/x86_64-w64-mingw32/lib/liblzma-5.dll.a -Wl,-rpath,'$$ORIGIN'
			endif	
		else
			BAE_LIBS += -llzma
		endif
	endif
endif

ifeq ($(BUILD_GUI),1)
	BAE_FLAGS += -D_ZEFI_GUI=1
	SRC_BIN	:= src/gui/gui_theme.c \
		src/gui/gui_widgets.c \
		src/gui/gui_text.c \
		src/gui/gui_midi_vkbd.c \
		src/gui/gui_export.c \
		src/gui/gui_dialogs.c \
		src/gui/gui_bae.c \
		src/gui/gui_settings.c \
		src/gui/gui_panels.c \
		src/gui/gui_main.c
	
	# Add debug console for DEBUG builds
	ifeq ($(DEBUG),1)
		SRC_BIN += src/gui/gui_debug_console.c
	endif
else
	ifeq ($(RMFINFO),1)
		# libNeoBAE srcs + rmfinfo.c
		SRC_BIN	:= $(SRC) src/rmfinfo/rmfinfo.c
	else
		ifeq ($(INSTDUMP),1)
			# libNeoBAE srcs + instdump.c
			SRC_BIN	:= $(SRC) src/rmfinfo/instdump.c
		else
			ifeq ($(RMF2MID),1)
				# libNeoBAE srcs + rmf2mid.c
				SRC_BIN	:= $(SRC) src/rmf2mid/rmf2mid.c
			else
				ifeq ($(MID2RMF),1)
					# libNeoBAE srcs + mid2rmf.c
					SRC_BIN	:= $(SRC) src/mid2rmf/mid2rmf.c
				else
					ifeq ($(MOD2RMF),1)
						# libNeoBAE srcs + split mod2rmf sources
						SRC_BIN	:= $(SRC) src/mod2rmf/mod2rmf.c src/mod2rmf/mod2rmf_mod.c src/mod2rmf/mod2rmf_s3m.c src/mod2rmf/mod2rmf_encoder.c src/mod2rmf/mod2rmf_resampler.c
					else
						ifeq ($(MID2RMI),1)
							# libNeoBAE srcs + mid2rmi.c
							SRC_BIN	:= $(SRC) src/mid2rmi/mid2rmi.c
						else
							ifeq ($(BANKRECOMP),1)
								# libNeoBAE srcs + bankrecomp.c
								SRC_BIN	:= $(SRC) src/bankrecomp/bankrecomp.c
							else
								ifeq ($(NBSTUDIO),1)
									SRC_BIN := $(SRC) \
										src/rmfeditor_wx/editor_main.cpp \
										src/rmfeditor_wx/editor_bank.cpp \
										src/rmfeditor_wx/editor_instrument_ext_dialog.cpp \
										src/rmfeditor_wx/editor_metadata_dialog.cpp \
										src/rmfeditor_wx/editor_pianoroll_panel.cpp \
										src/rmfeditor_wx/batch_compress_dialog.cpp
									BAE_FLAGS += $(shell pkg-config --cflags gtk+-3.0) $(shell pkg-config --cflags glib-2.0)
									BAE_LIBS += -lz $(shell pkg-config --libs gtk+-3.0) $(shell pkg-config --libs glib-2.0)
								else
									# playbae = libNeoBAE srcs + playbae.c
									SRC_BIN	:= $(SRC) src/playbae/playbae.c
								endif
							endif
						endif
					endif
				endif
			endif
		endif
	endif
endif

ifeq ($(KARAOKE),1)
	ifneq ($(BUILD_GUI),)
		SRC_BIN += src/gui/gui_karaoke.c
	endif
endif

ifeq ($(ENABLE_MIDI_HW),1)
	ifneq ($(BUILD_GUI),)
		# RtMidi (C wrapper) - provide real-time MIDI input for GUI
		BAE_FLAGS += -DSUPPORT_MIDI_HW=1
		SRC_BIN +=  src/gui/gui_midi_hw.c \
			src/gui/gui_midi_hw_input.c \
			src/gui/gui_midi_hw_output.c \
			src/thirdparty/rtmidi/rtmidi_c.cpp \
			src/thirdparty/rtmidi/RtMidi.cpp
	endif
endif

ifeq ($(PLAYLIST),1)
	ifneq ($(BUILD_GUI),)
		BAE_FLAGS += -DSUPPORT_PLAYLIST=1
		SRC_BIN +=  src/gui/gui_playlist.c
	endif
endif


ifeq ($(LOGFILE),1)
	BAE_FLAGS += -DOUTPUT_TO_LOGFILE=1
endif

ifeq ($(WINDOWS),1)
	ifneq ($(filter 1,$(FLAC_DEC) $(FLAC_ENC)),)
		INC_PATH += -Isrc/thirdparty/flac/src/share/win_utf8_io
		BAE_FLAGS += -DFLAC__NO_DLL
		SRC += src/thirdparty/flac/src/share/win_utf8_io/win_utf8_io.c
		SRC_BIN += src/thirdparty/flac/src/share/win_utf8_io/win_utf8_io.c
	endif
endif

ifeq ($(KARAOKE),1)
	BAE_FLAGS += -DSUPPORT_KARAOKE=1
endif

ifeq ($(BAESCRIPT),1)
	BAE_FLAGS += -DSUPPORT_BAESCRIPT=1
	INC_PATH += -Isrc/script
	SRC_BIN += src/script/baescript.c \
		src/script/baescript_lexer.c \
		src/script/baescript_parser.c \
		src/script/baescript_vm.c
	ifneq ($(BUILD_GUI),)
		SRC_BIN += src/gui/gui_script_editor.c
	endif
endif


ifeq ($(WASM),1)
	INC_PATH	+= -I../../emsdk/upstream/emscripten/cache/sysroot/include
	BAE_LIBS	+= -L../../emsdk/upstream/emscripten/cache/sysroot/lib
endif

OBJ_DIR 	:= $(BUILD_DIR)obj/
# Create unique object names by including source directory info for conflicting files
SRC_UNIQUE := $(SRC)
SRC_UNIQUE := $(subst src/thirdparty/flac/src/libFLAC/lpc.c,src/thirdparty/flac/src/libFLAC/flac_lpc.c,$(SRC_UNIQUE))
SRC_UNIQUE := $(subst src/thirdparty/flac/src/libFLAC/window.c,src/thirdparty/flac/src/libFLAC/flac_window.c,$(SRC_UNIQUE))
SRC_UNIQUE := $(subst src/thirdparty/libvorbis/lib/lpc.c,src/thirdparty/libvorbis/lib/vorbis_lpc.c,$(SRC_UNIQUE))
SRC_UNIQUE := $(subst src/thirdparty/libvorbis/lib/window.c,src/thirdparty/libvorbis/lib/vorbis_window.c,$(SRC_UNIQUE))
OBJ 		:= $(addprefix $(OBJ_DIR),$(addsuffix .o,$(notdir $(basename ${SRC_UNIQUE}))))

SRC_BIN_UNIQUE := $(SRC_BIN)
SRC_BIN_UNIQUE := $(subst src/thirdparty/flac/src/libFLAC/lpc.c,src/thirdparty/flac/src/libFLAC/flac_lpc.c,$(SRC_BIN_UNIQUE))
SRC_BIN_UNIQUE := $(subst src/thirdparty/flac/src/libFLAC/window.c,src/thirdparty/flac/src/libFLAC/flac_window.c,$(SRC_BIN_UNIQUE))
SRC_BIN_UNIQUE := $(subst src/thirdparty/libvorbis/lib/lpc.c,src/thirdparty/libvorbis/lib/vorbis_lpc.c,$(SRC_BIN_UNIQUE))
SRC_BIN_UNIQUE := $(subst src/thirdparty/libvorbis/lib/window.c,src/thirdparty/libvorbis/lib/vorbis_window.c,$(SRC_BIN_UNIQUE))
OBJ_BIN 	:= $(addprefix $(OBJ_DIR),$(addsuffix .o,$(notdir $(basename ${SRC_BIN_UNIQUE}))))

ifeq ($(BUILD_GUI),1)

BAE_FLAGS += -D_ZEFI_GUI=1

# If EMBED_TTF_FONT specified, generate embedded_font.h and define EMBED_TTF_FONT
ifeq ($(EMBED_FONT),1)
ifdef EMBED_TTF_FONT
BAE_FLAGS += -DEMBED_TTF_FONT -I$(OBJ_DIR)

EMBED_FONT_HEADER := $(OBJ_DIR)embedded_font.h
$(EMBED_FONT_HEADER): $(EMBED_TTF_FONT) ../scripts/create_embedded_font_h.py
	@echo @embed $<
	@mkdir -p $(dir $(EMBED_FONT_HEADER))
	@python3 ../scripts/create_embedded_font_h.py $(EMBED_TTF_FONT) $(EMBED_FONT_HEADER)

$(OBJ_DIR)gui_main.o: $(EMBED_FONT_HEADER)
endif # EMBED_FONT_HEADER
endif

endif # BUILD_GUI

# If EMBED_PATCH_FILE specified, generate BAEPatches.h that embeds the binary bank
ifeq ($(EMBED_PATCHES),1)
ifdef EMBED_PATCH_FILE
BAE_FLAGS += -D_BUILT_IN_PATCHES=1 -I$(OBJ_DIR)

EMBED_PATCH_HEADER := $(OBJ_DIR)BAEPatches.h
$(EMBED_PATCH_HEADER): $(EMBED_PATCH_FILE) ../scripts/create_embedded_patches_h.py
	@echo @embed $<
	@mkdir -p $(dir $(EMBED_PATCH_HEADER))
	@python3 ../scripts/create_embedded_patches_h.py $(EMBED_PATCH_FILE) $(EMBED_PATCH_HEADER)
$(OBJ_DIR)NeoBAE.o: $(EMBED_PATCH_HEADER)

# Ensure generated header is available to build when EMBED_PATCH_FILE is used
endif # EMBED_PATCH_FILE
endif

# Rules for compiling source files to object files
# Create a function to map source files to object files with unique names for conflicts
define make_obj_rule
$(OBJ_DIR)$(basename $(notdir $(subst src/thirdparty/flac/src/libFLAC/lpc.c,flac_lpc.c,$(subst src/thirdparty/flac/src/libFLAC/window.c,flac_window.c,$(subst src/thirdparty/libvorbis/lib/lpc.c,vorbis_lpc.c,$(subst src/thirdparty/libvorbis/lib/window.c,vorbis_window.c,$(1))))))).o: $(1)
	@echo @compile $$<
	@mkdir -p $(OBJ_DIR)
	$(SILENT)$(if $(filter %.cpp,$(1)),${CXX} -c ${CXXFLAGS},${CC} -c ${CFLAGS}) $$< -o $$@
endef

ifeq ($(USE_SDL3),1)
	BAE_FLAGS += -D_USING_SDL3=1
endif
#### End Makefile.common
