/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zefie_NeoBAE_Mixer */

#ifndef _Included_com_zefie_NeoBAE_Mixer
#define _Included_com_zefie_NeoBAE_Mixer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zefie_NeoBAE_Mixer
 * Method:    _newMixer
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_zefie_NeoBAE_Mixer__1newMixer
  (JNIEnv *, jclass);

/*
 * Class:     com_zefie_NeoBAE_Mixer
 * Method:    _deleteMixer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zefie_NeoBAE_Mixer__1deleteMixer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zefie_NeoBAE_Mixer
 * Method:    _openMixer
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1openMixer
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1disengageAudio
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1reengageAudio
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1isAudioEngaged
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1setDefaultReverb
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1addBankFromFile
  (JNIEnv *, jclass, jlong, jstring);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1setMasterVolume
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_zefie_NeoBAE_Mixer
 * Method:    _setAndroidOutputGainBoost
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1setAndroidOutputGainBoost
  (JNIEnv *, jclass, jint);

JNIEXPORT jstring JNICALL Java_com_zefie_NeoBAE_Mixer__1getBankFriendlyName
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1addBankFromMemoryWithFilename
  (JNIEnv *, jclass, jlong, jbyteArray, jstring);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1startOutputToFile
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1serviceOutputToFile
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1stopOutputToFile
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1setSpanDCFix
  (JNIEnv *, jclass, jboolean);

JNIEXPORT jboolean JNICALL Java_com_zefie_NeoBAE_Mixer__1getSpanDCFix
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Mixer__1setClassicChorus
  (JNIEnv *, jclass, jboolean);

JNIEXPORT jboolean JNICALL Java_com_zefie_NeoBAE_Mixer__1getClassicChorus
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
