/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zefie_NeoBAE_Sound */

#ifndef _Included_com_zefie_NeoBAE_Sound
#define _Included_com_zefie_NeoBAE_Sound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _newNativeSound
 * Signature: (I)I
 */
JNIEXPORT jlong JNICALL Java_com_zefie_NeoBAE_Sound__1newNativeSound
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _loadSound
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jlong JNICALL Java_com_zefie_NeoBAE_Sound__1loadSound__ILjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _loadSound
 * Signature: (ILandroid/content/res/AssetManager;Ljava/lang/String;)I
 */
JNIEXPORT jlong JNICALL Java_com_zefie_NeoBAE_Sound__1loadSound__ILandroid_content_res_AssetManager_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _startSound
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1startSound
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _stopSound
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1stopSound
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _pauseSound
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1pauseSound
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _resumeSound
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1resumeSound
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _isSoundPaused
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zefie_NeoBAE_Sound__1isSoundPaused
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _isSoundDone
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zefie_NeoBAE_Sound__1isSoundDone
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _setSoundVolume
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1setSoundVolume
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _getSoundVolume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1getSoundVolume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _getSoundPositionFrames
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1getSoundPositionFrames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _getSoundLengthFrames
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1getSoundLengthFrames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _getSoundSampleRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1getSoundSampleRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zefie_NeoBAE_Sound
 * Method:    _normalizeFromPeak
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_zefie_NeoBAE_Sound__1normalizeFromPeak
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
