BAE_BUILT_IN_PATCHES	:= 1
BAE_API			:= SDL3
BUILD_GUI   	:= 1
WINDOWS 		:= 1
ifneq ($(NOAUTO),1)
ENABLE_MIDI_HW	:= 1
endif
include inc/Makefile.common
TARGET_BIN		:= $(TARGET_NAME).exe
SOURCE_DIR = $(CURDIR)

ifeq ($(BITS),32)
	CROSS := i686-w64-mingw32-
else
	CROSS := x86_64-w64-mingw32-
endif

ifeq ($(BITS),32)
    ARCH		:= -static
    CC		:= i686-w64-mingw32-gcc
    CXX		:= i686-w64-mingw32-g++
ifneq ($(filter %.cpp,$(SRC) $(SRC_BIN)),)
LD			:= $(CXX)
else
LD			:= $(CC)
endif
    AR      	:= i686-w64-mingw32-ar
    STRIP      	:= i686-w64-mingw32-strip
    DLLTOOL		:= i686-w64-mingw32-dlltool
	WINDRES		:= i686-w64-mingw32-windres
    OPTI            := -O2 -fPIC
    ifeq ($(LDEBUG),1)
        OPTI := -g -O0 -ggdb3 -fPIC
    endif 
    CFLAGS  	:= $(ARCH) $(OPTI) $(INC_PATH) -D_THREAD_SAFE -Wno-unused-value -DEMBED_FONT_TTF
else
    ARCH		:= -static
    CC		:= x86_64-w64-mingw32-gcc
    CXX		:= x86_64-w64-mingw32-g++
ifneq ($(filter %.cpp,$(SRC) $(SRC_BIN)),)
LD			:= $(CXX)
else
LD			:= $(CC)
endif
    AR      	:= x86_64-w64-mingw32-ar
    STRIP      	:= x86_64-w64-mingw32-strip
    DLLTOOL		:= x86_64-w64-mingw32-dlltool
	WINDRES		:= x86_64-w64-mingw32-windres
    OPTI            := -O2 -fPIC
    ifeq ($(LDEBUG),1)
        OPTI := -g -O0 -ggdb3 -fPIC
    endif 
    CFLAGS  	:= $(ARCH) $(OPTI) $(INC_PATH) -D_THREAD_SAFE -Wno-unused-value -DEMBED_FONT_TTF
endif


ifneq ($(ENABLE_MIDI_HW),)
	# WinMM MIDI HW Support
	CFLAGS += -D__WINDOWS_MM__ 
endif

ifneq ($(BAE_FLAGS),)
	CFLAGS	+= $(BAE_FLAGS)
endif

include inc/Makefile.versioning
CFLAGS		+= -D_VERSION=\""$(VERSION)"\"

CXXFLAGS 	:= $(CFLAGS)
LDFLAGS		:= $(ARCH) $(OPTI)


ifneq ($(BAE_LD_FLAGS),)
	LDFLAGS += $(BAE_LD_FLAGS)
endif

ifneq ($(LDEBUG),1)
	LDFLAGS += -s
endif
ifeq ($(BITS),32)
CFLAGS  += -I../deps/win/SDL3/i686-w64-mingw32/include -I../deps/win/SDL3/i686-w64-mingw32/include/SDL3 -I../deps/win/SDL3_ttf/i686-w64-mingw32/include
CXXFLAGS  += -I../deps/win/SDL3/i686-w64-mingw32/include -I../deps/win/SDL3/i686-w64-mingw32/include/SDL3 -I../deps/win/SDL3_ttf/i686-w64-mingw32/include
LDFLAGS += -L../deps/win/SDL3/i686-w64-mingw32/lib -L../deps/win/SDL3_ttf/i686-w64-mingw32/lib
else
CFLAGS  += -I../deps/win/SDL3/x86_64-w64-mingw32/include -I../deps/win/SDL3/x86_64-w64-mingw32/include/SDL3 -I../deps/win/SDL3_ttf/x86_64-w64-mingw32/include
CXXFLAGS  += -I../deps/win/SDL3/x86_64-w64-mingw32/include -I../deps/win/SDL3/x86_64-w64-mingw32/include/SDL3 -I../deps/win/SDL3_ttf/x86_64-w64-mingw32/include
LDFLAGS += -L../deps/win/SDL3/x86_64-w64-mingw32/lib -L../deps/win/SDL3_ttf/x86_64-w64-mingw32/lib
endif

LIBS = \
	-lmingw32 \
	-lSDL3.dll \
	-lSDL3_ttf.dll \
	-lwinmm \
	-lole32 \
	-lcomdlg32

ifneq ($(BAE_LIBS),)
	LIBS += $(BAE_LIBS)
endif	

all: $(TARGET_LIB).a ${TARGET_LIB}.dll $(TARGET_BIN) $(TARGET_OUT)RegisterFiletypes.exe

$(OBJ_DIR)winreg_filetypes.o:
	$(CC) $(CFLAGS) -DUNICODE -D_UNICODE -c src/gui/winreg_filetypes.c -o $(OBJ_DIR)winreg_filetypes.o

$(TARGET_OUT)RegisterFiletypes.exe: $(OBJ_DIR)winreg_filetypes.o
	@mkdir -p $(TARGET_OUT)
	${WINDRES} src/gui/winreg_filetypes.rc $(OBJ_DIR)winreg_filetypes_res.o; \
	${LD} -o $(TARGET_OUT)RegisterFiletypes.exe ${LDFLAGS} $(OBJ_DIR)winreg_filetypes.o $(OBJ_DIR)winreg_filetypes_res.o -Wl,--subsystem,windows -lshlwapi -lgdi32 -lcomctl32

$(TARGET_LIB).a: $(OBJ_BIN)
	@mkdir -p $(TARGET_OUT)
	$(AR) rcs $(TARGET_OUT)$(TARGET_LIB).a $(OBJ_BIN)

$(TARGET_LIB).dll: ${OBJ_BIN}
	@mkdir -p $(TARGET_OUT)
	@$(DLLTOOL) --export-all --export-all-symbols -e $(OBJ_DIR)exports.o -z $(OBJ_DIR)$(TARGET_LIB).def2 $(OBJ_BIN)
	@echo "EXPORTS" > $(OBJ_DIR)$(TARGET_LIB).def
	@cat $(OBJ_DIR)$(TARGET_LIB).def2 | grep "BAE" >> $(OBJ_DIR)$(TARGET_LIB).def
	@rm -f $(OBJ_DIR)$(TARGET_LIB).def2 $(OBJ_DIR)exports.o
	@$(DLLTOOL) -e $(OBJ_DIR)exports.o -d $(OBJ_DIR)$(TARGET_LIB).def -l $(TARGET_OUT)$(TARGET_LIB).lib $(OBJ_BIN)
	$(CC) -shared $(LDFLAGS) ${OBJ_BIN} $(OBJ_DIR)exports.o -Wl,--subsystem,windows -o $(TARGET_OUT)${TARGET_LIB}.dll -Wl,--out-implib,$(TARGET_OUT)$(TARGET_LIB).dll.a -Wl,--export-all-symbols -Wl,--enable-auto-image-base -lstdc++ ${LIBS}

	@if [ "$(USE_FLUIDSYNTH)" = "1" ]; then \
		if [ "$(BITS)" = "32" ]; then \
			cp ../deps/win/FluidSynth/i686-w64-mingw32/bin/libfluidsynth-3.dll $(TARGET_OUT) 2>/dev/null || true; \
			cp ../deps/win/FluidSynth/i686-w64-mingw32/bin/sndfile.dll $(TARGET_OUT) 2>/dev/null || true; \
		else \
			cp ../deps/win/FluidSynth/x86_64-w64-mingw32/bin/libfluidsynth-3.dll $(TARGET_OUT) 2>/dev/null || true; \
			cp ../deps/win/FluidSynth/x86_64-w64-mingw32/bin/sndfile.dll $(TARGET_OUT) 2>/dev/null || true; \
		fi; \
	fi

	@if [ "$(BITS)" = "32" ]; then \
		cp ../deps/win/SDL3/i686-w64-mingw32/bin/SDL3.dll $(TARGET_OUT) 2>/dev/null || true; \
		cp ../deps/win/SDL3_ttf/i686-w64-mingw32/bin/SDL3_ttf.dll $(TARGET_OUT) 2>/dev/null || true; \
	else \
		cp ../deps/win/SDL3/x86_64-w64-mingw32/bin/SDL3.dll $(TARGET_OUT) 2>/dev/null || true; \
		cp ../deps/win/SDL3_ttf/x86_64-w64-mingw32/bin/SDL3_ttf.dll $(TARGET_OUT) 2>/dev/null || true; \
	fi

$(TARGET_BIN): ${OBJ_BIN} $(TARGET_LIB).dll
	@mkdir -p $(TARGET_OUT)Banks
	$(SHELL) src/banks/copy.sh $(TARGET_OUT)Banks
	${WINDRES} src/gui/zefidi.rc $(OBJ_DIR)zefidi.o; \
	${LD} -o $(TARGET_OUT)${TARGET_BIN} ${LDFLAGS} ${OBJ_BIN} $(OBJ_DIR)zefidi.o -Wl,--subsystem,windows -L./bin -lNeoBAE ${LIBS}; \

# Rules for compiling source files to object files
$(OBJ_DIR)%.o : %.cpp
	@echo @compile $<
	@mkdir -p $(OBJ_DIR)
	$(SILENT)${CXX} -c ${CXXFLAGS} $< -o $@

$(OBJ_DIR)%.o : %.c
	@echo @compile $<
	@mkdir -p $(OBJ_DIR)
	$(SILENT)${CC} -c ${CFLAGS} $< -o $@

clean:
	@rm -rf $(TARGET_OUT)
	@rm -rf $(OBJ_DIR)
	@rm -rf $(BUILD_DIR)
	@rm -rf $(TEST_OUT_DIR)
	@echo Cleaned!

# Generate rules for all unique source files (same approach as top-level Makefile)
ALL_SOURCES := $(sort $(SRC) $(SRC_BIN))
$(foreach src,$(ALL_SOURCES),$(eval $(call make_obj_rule,$(src))))

include inc/Makefile.tests
