#!/usr/bin/env python3
"""Generate C header(s) embedding TTF font(s) as byte arrays.

Legacy (zefidi):
  python create_embedded_font_h.py path/to/font.ttf out/embedded_font.h [--symbol-name NAME]

Multi-font (nbeditor):
  python create_embedded_font_h.py out/nbeditor_embedded_fonts.h \\
      --font path/Regular.ttf liberation_sans_regular \\
      --font path/Italic.ttf liberation_sans_italic

Legacy output defines:
  static const unsigned char <symbol>_data[];
  static const unsigned int <symbol>_size;
  #define embedded_font_data <symbol>_data
  #define embedded_font_size <symbol>_size
"""
from __future__ import annotations

import os
import sys


def write_array(f, sym_name: str, data: bytes) -> None:
    f.write(f"static const unsigned char {sym_name}_data[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk))
        f.write(",\n")
    f.write("};\n")
    f.write(f"static const unsigned int {sym_name}_size = {len(data)};\n\n")


def load_font(path: str) -> bytes:
    if not os.path.isfile(path):
        raise FileNotFoundError(f"font file not found: {path}")
    with open(path, "rb") as fh:
        return fh.read()


def write_header(out_path: str, fonts: list[tuple[str, str, bytes]], *, legacy_aliases: bool) -> None:
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    guard = "GUI_EMBEDDED_FONT_H"
    if not legacy_aliases:
        base = os.path.splitext(os.path.basename(out_path))[0].upper()
        base = "".join(ch if ch.isalnum() else "_" for ch in base)
        guard = f"{base}_H"
    with open(out_path, "w", newline="\n") as f:
        f.write("// Auto-generated by create_embedded_font_h.py. DO NOT EDIT.\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write("#include <stddef.h>\n#include <stdint.h>\n\n")
        for _path, sym_name, data in fonts:
            write_array(f, sym_name, data)
        if legacy_aliases and fonts:
            sym_name = fonts[0][1]
            f.write(f"#define embedded_font_data {sym_name}_data\n")
            f.write(f"#define embedded_font_size {sym_name}_size\n\n")
        f.write(f"#endif /* {guard} */\n")
    total = sum(len(data) for _p, _s, data in fonts)
    stat_info = os.stat(out_path)
    print(
        f"Wrote {out_path} ({stat_info.st_size} bytes) as C array "
        f"({total} bytes raw, {len(fonts)} font(s))"
    )


def parse_multi(argv: list[str]) -> list[tuple[str, str]]:
    fonts: list[tuple[str, str]] = []
    i = 0
    while i < len(argv):
        if argv[i] == "--font":
            if i + 2 >= len(argv):
                raise SystemExit("Usage: --font <ttf> <symbol-name>")
            fonts.append((argv[i + 1], argv[i + 2]))
            i += 3
            continue
        raise SystemExit(f"Unexpected argument: {argv[i]}")
    if not fonts:
        raise SystemExit("No --font entries provided")
    return fonts


def main() -> int:
    if len(sys.argv) < 3:
        print(
            "Usage:\n"
            "  create_embedded_font_h.py <font.ttf> <out_header> [--symbol-name NAME]\n"
            "  create_embedded_font_h.py <out_header> --font <ttf> <symbol> "
            "[--font <ttf> <symbol> ...]"
        )
        return 1

    # Multi-font mode: first arg is output header, then --font pairs.
    if "--font" in sys.argv:
        out_path = sys.argv[1]
        font_specs = parse_multi(sys.argv[2:])
        fonts = [(path, sym, load_font(path)) for path, sym in font_specs]
        write_header(out_path, fonts, legacy_aliases=False)
        return 0

    font_path = sys.argv[1]
    out_path = sys.argv[2]
    sym_name = "embedded_font"
    if "--symbol-name" in sys.argv:
        idx = sys.argv.index("--symbol-name")
        if idx + 1 < len(sys.argv):
            sym_name = sys.argv[idx + 1]
    data = load_font(font_path)
    write_header(out_path, [(font_path, sym_name, data)], legacy_aliases=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
