buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.1.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.0'
        classpath 'org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.3.0'
        classpath 'com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:2.3.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}