@echo off
setlocal EnableExtensions EnableDelayedExpansion

rem =============================================================================
rem gen_version.bat — write Version.gen.h using the same rules as CMakeLists.txt /
rem neobae/inc/Makefile.versioning (git short hash, tag-on-HEAD, -dirty).
rem =============================================================================

set "SCRIPT_DIR=%~dp0"
set "OUT_FILE=%SCRIPT_DIR%Version.gen.h"

set "REPO_ROOT="
for /f "delims=" %%I in ('git -C "%SCRIPT_DIR%" rev-parse --show-toplevel 2^>nul') do set "REPO_ROOT=%%I"
if not defined REPO_ROOT (
  pushd "%SCRIPT_DIR%..\.." >nul 2>&1
  set "REPO_ROOT=!CD!"
  popd >nul
)

set "GIT_COMMIT="
set "GIT_DIRTY="
set "GIT_TAG_COMMIT="
set "GIT_TAG="
set "GIT_DATE="

where git >nul 2>&1
if errorlevel 1 goto :compute_version
if not defined REPO_ROOT goto :compute_version

for /f "delims=" %%I in ('git -C "!REPO_ROOT!" rev-parse --short HEAD 2^>nul') do set "GIT_COMMIT=%%I"

rem Any porcelain output means dirty working tree.
git -C "!REPO_ROOT!" status --porcelain 2>nul | findstr /R "." >nul 2>&1
if not errorlevel 1 set "GIT_DIRTY=1"

for /f "delims=" %%I in ('git -C "!REPO_ROOT!" rev-list --abbrev-commit --tags --max-count=1 2^>nul') do set "GIT_TAG_COMMIT=%%I"
if defined GIT_TAG_COMMIT (
  for /f "delims=" %%I in ('git -C "!REPO_ROOT!" describe --abbrev=0 --tags !GIT_TAG_COMMIT! 2^>nul') do set "GIT_TAG=%%I"
)

for /f "delims=" %%I in ('git -C "!REPO_ROOT!" log -1 --format^=%%cd --date=format:%%Y%%m%%d 2^>nul') do set "GIT_DATE=%%I"

:compute_version
set "VERSION="
if not defined GIT_COMMIT (
  if not defined GIT_DATE (
    for /f "delims=" %%I in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd"') do set "GIT_DATE=%%I"
  )
  set "VERSION=!GIT_DATE!"
) else (
  if defined GIT_TAG (
    if /I "!GIT_COMMIT!"=="!GIT_TAG_COMMIT!" (
      set "VERSION=!GIT_TAG!"
      if /I "!VERSION:~0,1!"=="v" set "VERSION=!VERSION:~1!"
    ) else (
      set "VERSION=git-!GIT_COMMIT!"
    )
  ) else (
    set "VERSION=git-!GIT_COMMIT!"
  )
  if defined GIT_DIRTY set "VERSION=!VERSION!-dirty"
)

if not defined VERSION set "VERSION=unknown"

set "TMP_FILE=%OUT_FILE%.tmp"
(
  echo #pragma once
  echo // Generated by gen_version.bat — do not edit.
  echo #define FOO_NEOBAE_VERSION_STRING "!VERSION!"
) > "%TMP_FILE%"

fc /b "%TMP_FILE%" "%OUT_FILE%" >nul 2>&1
if errorlevel 1 (
  move /Y "%TMP_FILE%" "%OUT_FILE%" >nul
) else (
  del "%TMP_FILE%" >nul 2>&1
)

echo foo_neobae version: !VERSION!
exit /b 0
