package com.zefie.neobaemc.net;

import com.zefie.neobaemc.NeoBAEMC;
import io.netty.buffer.ByteBuf;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.ResourceLocation;

/**
 * Client → Server: "please stream me the (server-side cached/transcoded)
 * Ogg/Vorbis bytes for this URL". The {@code streamId} is generated by the
 * client and echoed back on every {@link SoundChunkPayload} so the client
 * can route chunks to the right pending request.
 */
public record SoundRequestPayload(int streamId, String url) implements CustomPacketPayload {

    public static final Type<SoundRequestPayload> TYPE =
            new Type<>(ResourceLocation.fromNamespaceAndPath(NeoBAEMC.MODID, "sound_request"));

    public static final StreamCodec<ByteBuf, SoundRequestPayload> CODEC =
            StreamCodec.composite(
                    ByteBufCodecs.VAR_INT, SoundRequestPayload::streamId,
                    ByteBufCodecs.STRING_UTF8, SoundRequestPayload::url,
                    SoundRequestPayload::new
            );

    @Override
    public Type<? extends CustomPacketPayload> type() { return TYPE; }
}
